### ISSUE TITLE
--wake-path (or --exclude-path)?

### ISSUE THREAD

**Issue by samh-sifive** [sifive/wake#104]
Not necessarily recommending this as a solution, but @jackkoenig and I have heard from some users that they run into problems in their `wit` workspace when a package revision change obviates a checked out package. `wit` doesn't currently delete packages in this case, in part because they might have user changes.

The problem is that a package that is no longer technically part of their workspace can still change how `wake` runs. As a trivial example, let's say someone has been developing using wake 0.1, and package `a` depends on package `b` depends on package `c`.

In the process of updating to wake 0.13, package `a` now depends on package `c`, but package `b` is no longer used. Wake will still try to load any `.wake` files therein (which are probably no longer compatible, due to the version change), so the build will fail.

One solution of course is for `wit` to delete any packages that aren't part of the current resolved manifest. But given that workspaces are areas of active development, this seems a bit draconian. Another solution would be for wake to accept a `--wake-path` argument where the user could specify which subdirectories to look in (and `wit` could emit this path, so one could run `wake --wake-path 'wit --paths'`

Thoughts?

**Comment by terpstra** [comment]
Just to be sure I understand: the requested functionality is to be able to limit which wake files are read in the workspace?

To be honest, it seems to me like the current behaviour of both wit and wake is probably correct. We could add this feature to wake, but using it would be quite cumbersome.

Wit might consider issuing a warning that there is a unreferenced repository in the workspace, with a suggested commands for how to add it as an explicitly requested repository or delete it.

**Comment by samh-sifive** [comment]
I agree that `wit` can/should provide better info here as well. @jackkoenig and I have talked about including this in `wit status`. `wit update` could likewise provide info about this.

The real question is about the expectation for the workspace. Should it always be "clean" (i.e. no unreferenced packages/temp work areas)? This issue came up because a couple people who are trying to use wit/wake for development were finding that to be onerous. @jackkoenig , do you have any strong opinions here?

**Comment by terpstra** [comment]
Closing, because I don't think we're going to change wake for this.
