### ISSUE TITLE
filter getStdfoo for color and add getStdfooRaw

### ISSUE THREAD

**Issue by JakeSiFive** [sifive/wake#1112]
After https://github.com/sifive/wake/pull/1109 lands jobs will now run in psuedoterminals which will trick them into emitting color. We probably have a lot of people trying to parse output from programs in wake unfortunately and this is going to break them. To avoid breaking them we need to filter the getJobStdout and getJobStderr strings but also provide an un-filtered way to get to that content.

If users want to avoid the psuedoterminal entirely they can wrap their program in a simple shell script like `myprogram -foo | tee /dev/null` and they should get clean output that way so I don't think we need to provide a way to run a program without a psuedoterminal.

**Comment by JakeSiFive** [comment]
@V-FEXrt

**Comment by ag-eitilt** [comment]
Now that I think about it, won't the pseudoterminal also have the potential to change the structure of the output for things that detect whether they're piping to a file descriptor as opposed to going direct to the terminal (`ls` vs. `ls | cat`)?  I agree that we can assume anyone who's using commands which are terminal-sensitive to that extent should probably explicitly use a wrapper pipe or *not machine-parse output which isn't guaranteed*, but this has the potential to be a bit disruptive.

**Comment by JakeSiFive** [comment]
Yes, `ls` will have extra newlines. Another issue is that some programs will add `\r` to newlines when outputting to a terminal specifically. We may have to also replace any `\r\n` combos with just `\n` but that may be overly heavy handed.

**Comment by V-FEXrt** [comment]
This is done!
