### ISSUE TITLE
Documentation on how to use wake?

### ISSUE THREAD

**Issue by hartwork** [sifive/wake#115]
Hi!

Where can I find documention on how to use wake?

Thanks, Sebastian

**Comment by jackkoenig** [comment]
The `doc` directory is the exiting documentation, in particular, check out the tutorial: https://github.com/sifive/wake/blob/master/doc/tutorial.md

The `doc` directory also contains syntax highlighting files for Vim and Emacs

**Comment by hartwork** [comment]
Thanks!

**Comment by terpstra** [comment]
Yeah. The documentation is severely lacking. This tool is still pretty ... fresh.
