### ISSUE TITLE
wake --last has unexpected whitespace lines

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#1154]
With this source file:
```
$ cat do.wake
package cli
from wake import _

global def do1 _ =
    "sleep 6; echo 1; echo foo > somefile;"
    | makePlan "some plan label 1" Nil
    | runJob

global def do2 _ =
    def _ = do1 Nil

    "sleep 1; echo 2; echo foo > somefile2;"
    | makePlan "some plan label 2" Nil
    | runJob
```
Running
```
$ wake do2
```
We see in `--last`
```
$ wake --last


# some plan label 1(1)
$ /usr/bin/dash -c sleep 6; echo 2 ; echo foo > somefile;


2


# some plan label 2(2)
$ /usr/bin/dash -c sleep 1; echo 1 ; echo foo > somefile2;


1
```

This could perhaps have less whitespace, such as
```
$ wake --last
# some plan label 1(1)
$ /usr/bin/dash -c sleep 6; echo 2 ; echo foo > somefile;
2

# some plan label 2(2)
$ /usr/bin/dash -c sleep 1; echo 1 ; echo foo > somefile2;
1
```

**Comment by V-FEXrt** [comment]
This was actually a specific request from @JakeSiFive 

The extra whitespace is to make explicit what came from the stdout/stderr and to help when some tool emits stdout/stderr which might be confused for the "metadata" from the output. My original implementation of this emitted "fence posts" which was a bit verbose

```
> wake --last
# some plan label 1(1)
$ /usr/bin/dash -c sleep 6; echo 2 ; echo foo > somefile;

---------------------------------------------------------------------------------
2
---------------------------------------------------------------------------------
```


The main issue is something like this

```
> wake --last
# some label 1
$ some job 1
# some label 2 
$ some job 2
2
```

where in the above `some job 1` emits
```
# some label 2 
$ some job 2
2
```
and thus causes confusion.

This is admitted extremely unlikely to happen however

**Comment by mmjconolly** [comment]
I think if someone wants to get a detailed view they can use `-v`, the non-v could optimize for the ordinary/likely cases

**Comment by mmjconolly** [comment]
My issue with the excess whitespace is that I don't mentally associate the stderr/stdout as coming from any particular job, it's just floating there

**Comment by mmjconolly** [comment]
strawman: For visual differentiation, we could indent all the stdout/stderr lines but leave the label/command unindented

**Comment by ag-eitilt** [comment]
This could also be solved if we tag the stream the line is from:
```
> wake --last
# some label 1
$ some job 1
[out]   # some label 2 
[out]   $ some job 2
[error] 2
```
Which also provides a place for timestamps (mayble less helpful for telling *time* itself, but I can see cases where elapsed time since the start is important).

**Comment by V-FEXrt** [comment]
> I think if someone wants to get a detailed view they can use -v, the non-v could optimize for the ordinary/likely cases

I think argument wins me over. We should go for minimal but useful for the default

**Comment by V-FEXrt** [comment]
@mmjconolly if there is a job without any output how should we print it?

With the changes for the stuff above we have two newlines when there isn't output. This is because we always add a newline after the command regardless of if we have stdout/stderr or not. Should we special case it?

no special case
```
$ wake --last
# some plan label 1(1)
$ /usr/bin/dash -c sleep 6; echo 2 ; echo foo > somefile;


# some plan label 2(2)
$ /usr/bin/dash -c sleep 1; echo 1 ; echo foo > somefile2;

```

vs 

special case
```
$ wake --last
# some plan label 1(1)
$ /usr/bin/dash -c sleep 6; echo 2 ; echo foo > somefile;

# some plan label 2(2)
$ /usr/bin/dash -c sleep 1; echo 1 ; echo foo > somefile2;
```

**Comment by mmjconolly** [comment]
Multiple newlines being displayed probably doesn't add much value to the user
I think so long as we avoid printing something like 
```
$ wake --last
# some plan label 1(1)
$ /usr/bin/dash -c sleep 6; echo 2 ; echo foo > somefile;
# some plan label 2(2)
$ /usr/bin/dash -c sleep 1; echo 1 ; echo foo > somefile2;
```
with no way to separate the jobs
