### ISSUE TITLE
wake --html: set title for page

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#1170]
When we generate a source listing via `wake --html > out.html` it could be nice if there were a `<title>` tag, so that when we have tabs open it's easier to identify

**Comment by mmjconolly** [comment]
It could also be nice to pretty-print the giant json at the end of the file. I'm guessing it would get compressed anyway if served by a webserver

**Comment by V-FEXrt** [comment]
Assigning this to @richardxia since the PR he just put up covers this

**Comment by richardxia** [comment]
Oh interesting, I didn't even realize this ticket existed. I only set the title because I ran an HTML validator and it told me that I should set one.
