### ISSUE TITLE
Wakebox --timeout option

### ISSUE THREAD

**Issue by ngraybeal** [sifive/wake#1177]
Can we add a`--timeout` option  to `wakebox` to terminate any child processes, except fuse-waked, after x time,. This would help ensure fuse-waked is able to report out the state of the wakebox, including its filesystem, upon termination.

I have a scenario in which wakebox is running in a cgroup and is sent a `SIGTERM` after a given timeout. Wakebox exits and does forward `SIGTERM` to the children, but before the children are able to handle the `SIGTERM`, the children are `SIGTERM` by the Parent process. This means fuse-waked is not able to report back any results. 

Perhaps another option `--kill-after` would be useful in that `--timeout` refers to when a `SIGTERM` is sent and `--kill-after` refers to how long after `--timeout` a `SIGKILL` should be sent.

I see some parallels in the following PR in ensuring fuse-waked is kept alive. 
https://github.com/sifive/wake/pull/1127

**Comment by mmjconolly** [comment]
This would be nice to have, it would help in environments where the user wants to be able to stop wakebox before an external timeout comes along and prevents a fuse-waked result output json from being written
