### ISSUE TITLE
VS Code extension reports same documentation for two different functions

### ISSUE THREAD

**Issue by bmitc** [sifive/wake#1207]
In `job.wake`, there is the code:

https://github.com/sifive/wake/blob/202d60261fdad0ad0fc0500be7a1fa3c8884dea0/share/wake/lib/system/job.wake#L196-L199

This code showcases an interesting bug in the VS Code extension (or its underlying systems that provides the documentation for a given function).

In this particular case, I expect `id` to have the documentation `# Set reasonable defaults ...` and `makeExecPlan` to have none. However, *both* `id` and `makeExecPlan` are given the documentation string.

![image](https://user-images.githubusercontent.com/65685447/231642530-132358d5-6f71-469e-b679-83ad3ec1c9c5.png)

![image](https://user-images.githubusercontent.com/65685447/231642423-5e633764-7458-4e44-9453-51aa5fd702aa.png)

The issue appears to be caused by there being no newlines between `id` and `makeExecPlan`. Adding one makes the documentation stay with `id` but disappear for `makeExecPlan`, which is the expected behavior, newline or not.

**Comment by V-FEXrt** [comment]
https://github.com/sifive/wake/pull/1336 should fix this  as we now  stop walking upwards when we see a non-comment line
