### ISSUE TITLE
Memoize is broken. Let's fix it.

### ISSUE THREAD

**Issue by terpstra** [sifive/wake#124]
Here's a straw-man:

```scala
def foo x y =
  memoize a b c ignore d e f
  <code with x+y+a+b+c+d+e+f in scope>

def box = foo 4 5 # creates a memoize map
def box2 = foo 5 6 # another independent memoize map

def v1 = box 1 2 3 4 5 6 # creates and saves key (1,2,3) into box
def v1again = box 1 2 3 7 8 9 # returns same result as v1.

def v2 = box 9 8 7 6 5 4 # create and saves key (9,8,7) into box

def v1box2 = box2 1 2 3 4 5 6 # creates and saves key (1,2,3) into box2
```

**Comment by terpstra** [comment]
The way this proposal differs from the old 'memoize' is that when you invoke a 'memoize' you create a new map on each invocation. So the ```foo``` above is a map factory with two keys. This means that all the in-scope variables prior to the memoize call are available inside the memoize body, but have the same value for all expressions evaluated and saved in the map.

Unlike the old memoize where you specify an integer, this proposal uses two keywords (names TBD): memoize and ignore. All the variables after the memoize act as the unique key for the map. All the variables after the ignore are additional arguments that must be supplied to the call, but are not part of the key for the map. These are the same as the ignored parameters for an old non-0 memoize.

The basic idea is that you have three categories of variables:
1. Those captured by the creation of the map. The same for all evaluations of the memoize body.
2. Those which act as the key for the memoize. Two calls to the map with the same key return the same value.
3. Those which are available to the map body, but are not part of the key.

It's category 3 variables which pose all the risky behavior. If you call the map with the same key, but different ignored variables, and the body would return a different result based on those ignored variables, you've now introduced a race condition.

It's also category 3 variables which allow you to break the type-system if they are variadic.

Ideally, we would never need category 3 variables, but experience has shown that we will in some cases.

**Comment by albertchen-sifive** [comment]
I like it. This is much easier than having to count arguments.

so if we have no ignore variables then it would look like this?
```
def foo x y =
  memoize a b c
  <code with x+y+a+b+c in scope>
```

also, can you put the memoize/ignore stuff on separate lines? for example could I do
```
def foo x y =
  memoize a b c
  ignore d e f
  <code with x+y+a+b+c in scope>
```

**Comment by terpstra** [comment]
I have a new proposal. We move the keyword to be an alternative to 'def':
```
def hax x y =
  target foo a b =
     ... expr ...
```

The new keyword is ```target``` (so you can use it at the top-level like: 'target myThing Unit = ...') and it uses all the terms before the '=' as the key to the memoized table. The table is generated at the point of the 'target' keyword. So in the example above, each call to hax will create a new table 'foo'. Within 'hax' you can then invoke 'foo' repeatedly, with the results memoized.

@jackkoenig proposed earlier that the 'ignored' values should not really be ignored. Rather, we should panic if they differ when the table key is identical. I like the proposal. I'm not 100% sure how to distinguish the terms that are the 'unique key' of the table from those which are just additional arguments. Here's a straw-man: an optional second '=' sign:

```
target foo x y = a b =
  ... expr ...
```

**Comment by jackkoenig** [comment]
I like the name `target`, I don't know how to distinguish between key and subkey, but `\` or `\\` seems better than `=`
```
target myCoolTarget name \\ module =
```

**Comment by terpstra** [comment]
I've opted for the single backslash syntax. I was surprised how easy it was to implement this. It's actually simpler than the old memoize implementation.
