### ISSUE TITLE
Can lsp-wake work with Emacs lsp?

### ISSUE THREAD

**Issue by davidmlw** [sifive/wake#1309]
I followed the Emacs tutorial https://emacs-lsp.github.io/lsp-mode/page/adding-new-language/ to add lsp-wake like this, but it does not work. Can lsp-wake work with Emacs lsp, what kind of Emacs lisp need to be added to support lsp-wake. I suppose lsp-wake follows the standard lsp protocol.

```
(with-eval-after-load 'lsp-mode
  (add-to-list 'lsp-language-id-configuration
               '(wake-mode . "lsp-wake"))

(lsp-register-client
 (make-lsp-client :new-connection (lsp-stdio-connection '("/usr/local/bin/wake" "--lsp"))
                  :activation-fn (lsp-activate-on "lsp-wake")
                  :server-id 'lsp-wake)))

;; or

(lsp-register-client
 (make-lsp-client :new-connection (lsp-stdio-connection "/usr/local/lib/wake/lsp-wake"))
                  :activation-fn (lsp-activate-on "lsp-wake")
                  :server-id 'lsp-wake)))

```

lsp-wake:
https://github.com/sifive/wake/blob/3cd5ce7547384f64d1d36cccc45cfe343358f00b/tools/lsp-wake/main.cpp#L639

wake-mode:
https://github.com/sifive/wake/blob/3cd5ce7547384f64d1d36cccc45cfe343358f00b/share/doc/wake/syntax/emacs/wake-mode.el#L192

**Comment by mmjconolly** [comment]
> but it does not work.

It would be helpful to describe what messages or failures you see when trying to use it

**Comment by V-FEXrt** [comment]
It _should_ be possible but as @mmjconolly mentioned we would need to see the error messages to help. Most editors have an LSP log for the client side so having that would be useful.

One other thing is that most LSP clients require you to specify where the "project root" is. For neovim this is done like this 

```lua
function find_wakeroot(name)
    dir = string.gsub(name, "/[^/]*$", "")
    if dir == "" then 
        return false 
    end
    if file_exists(dir .. "/.wakeroot") or file_exists(dir .. "/wake.db") then
        return dir
    else
        return find_wakeroot(dir)
    end
end

local configs = require('lspconfig.configs')
if not configs.wakelsp then
  configs.wakelsp = {
    default_config = {
      cmd = { '/path/to/wake', '--lsp' },
      filetypes = { 'wake' },
      root_dir = find_wakeroot,
      settings = {},
    },
  }
end
```

**Comment by davidmlw** [comment]
Emacs lsp asked the project root, and I filled the root. I am not sure how lsp or wak use this project root information, start the "wake --lsp" in the project root directory?

Thank you for the response. I checked the emacs messages and logs. It seems emacs lsp asked the root, and found the `lsp-wake` or `wake --lsp` server command but the server exited with fault. I didn't find the core dump file in the workspace nor in home. I wish the following logs helpful.

*Messages* buffer:
```LSP :: Connected to [lsp-wake:6655/starting /home/david/work/workspace].
LSP :: lsp-wake has exited (segmentation fault (core dumped))
Server lsp-wake:6655/starting exited (check corresponding stderr buffer for details). Do you want to restart it? (y or n) y
LSP :: Restarting LSP in buffer top.wake
LSP :: Connected to [lsp-wake:6664/starting /home/david/work/workspace].
LSP :: lsp-wake has exited (segmentation fault (core dumped))
Server lsp-wake:6664/starting exited (check corresponding stderr buffer for details). Do you want to restart it? (y or n) n
```

*lsp-log* buffer:
```
The following clients were selected based on priority: (server-id lsp-wake, priority 0)
Command "/opt/wake/36.1.0/bin/wake --lsp" is present on the path.
Command "/opt/wake/36.1.0/bin/wake --lsp" is present on the path.
Found the following clients for /home/david/work/yard-workspace/wake/top.wake: (server-id lsp-wake, priority 0)
The following clients were selected based on priority: (server-id lsp-wake, priority 0)
Command "/opt/wake/36.1.0/lib/wake/lsp-wake" is present on the path.
Command "/opt/wake/36.1.0/lib/wake/lsp-wake" is present on the path.
Found the following clients for /home/david/work/yard-workspace/wake/top.wake: (server-id lsp-wake, priority 0)
```

*lsp-wake* buffer: empty
```
```

*lsp-wake::stderr*:
```
Process lsp-wake stderr<1> finished

Process lsp-wake stderr finished

Process lsp-wake stderr<1> finished

Process lsp-wake stderr finished

```

**Comment by davidmlw** [comment]
I wrote a bash script as fake lsp-wake and log what it saw when called by Emacs lsp, and confirmed that the Emacs lsp just call the command in the root directory and no other arguments passed. It is like
```
cd project-root
/path/to/lsp-wake
```
How emacs lsp as a client to communicate with a lsp server? Through stdin and stdout? Otherwise they need negotiate a socket port number?

**Comment by davidmlw** [comment]
I think I know the root reason now.

https://github.com/sifive/wake/blob/ac3d97363e032909a3a02294a6da2c0772f4e765/tools/lsp-wake/main.cpp#L335
change to 
```
  receivedMessage.get("params").get("rootUri").value;
```
And emacs lsp works well.

That because Emacs use a deprecated version of lsp specification.

https://github.com/microsoft/vscode-languageserver-node/blob/2041784436fed53f4e77267a49396bca22a7aacf/protocol/src/common/protocol.ts#L1356-L1363C2

**Comment by davidmlw** [comment]
For the Emacs users, here is the solution:

```
(with-eval-after-load 'lsp-mode
  (add-to-list 'lsp-language-id-configuration
               '(wake-mode . "lsp-wake"))

(lsp-register-client
 (make-lsp-client :new-connection (lsp-stdio-connection '("/usr/local/bin/wake" "--lsp"))
                  :activation-fn (lsp-activate-on "lsp-wake")
                  :multi-root t
                  :server-id 'lsp-wake)))
```

**Comment by V-FEXrt** [comment]
@davidmlw Thanks for writing out all this information! Sorry I didn't respond sooner, I missed the comments on this thread.

Glad to hear you got it working! I'm going my best to bring the LSP more in line with the spec.


For completeness:
> How emacs lsp as a client to communicate with a lsp server? Through stdin and stdout? Otherwise they need negotiate a socket port number?

It communicates through stdin/stdout. The "client" (emacs in this case) launches the lsp as a child process then reads/writes to the stdin/stdout handles of the process
