### ISSUE TITLE
Wake Tutorial Updates

### ISSUE THREAD

**Issue by jinrudals** [sifive/wake#1461]
Hi team,

I've used old version `0.19.2` before, but with the current version, thins have been changed much.

For instance, `source` function returned `Path`, and with the current version it resturns `Result Path`.

However, `makePlan` still needs List Path for second argument.
I've just read through the doucments but there is no guide how to source files and use it in the makePlan arugment.

**Comment by ag-eitilt** [comment]
What document are you looking at?  Wake development is definitely continuing faster than the documentation, unfortunately, but the [section on working with files](https://github.com/sifive/wake/blob/master/share/doc/wake/tutorial.md#build-rules-with-file-inputs) does indeed talk about how you need to use `require Pass path = source "file.ext"` to get the `Path`, and the rest of that page should be essentially accurate.

**Comment by jinrudals** [comment]
My bad, not to fully understandd the `require` satement.

**Comment by ag-eitilt** [comment]
No worries!  It's a rather unique feature that most languages don't share, and it definitely takes some time to get used to it.  It's also unfortunately one of the parts of the language that generates the worst error messages (we definitely want to fix them, but doing so requires a surprisingly large refactor), so if you ever get an error saying that some type is wrong but you can't figure out why, look at your `require`s.
