### ISSUE TITLE
ubuntu install dependencies

### ISSUE THREAD

**Issue by davidmlw** [sifive/wake#172]
sudo dpkg -i wake_0.15.0-1_amd64.deb
(Reading database ... 116069 files and directories currently installed.)
Preparing to unpack wake_0.15.0-1_amd64.deb ...
Unpacking wake (0.15.0-1) over (0.15.0-1) ...
dpkg: dependency problems prevent configuration of wake:
 wake depends on libre2-1v5 (>= 20150701+dfsg); however:
  Package libre2-1v5 is not installed.

dpkg: error processing package wake (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 wake

**Comment by terpstra** [comment]
Just do an 'apt-get -f install' after you install the package.

**Comment by richardxia** [comment]
On modern versions of Ubuntu, you can also use `apt install` (which is different from `apt-get install`) to install a `.deb` file and automatically download its dependencies.

**Comment by terpstra** [comment]
I did not know this! Thanks.

**Comment by terpstra** [comment]
The problem turned out to be the wrong distribution.
