### ISSUE TITLE
Option to print output in JSON format

### ISSUE THREAD

**Issue by richardxia** [sifive/wake#178]
It would be useful if `wake` had a flag to tell it to return its output as a JSON string. This could be nice for returning data in a structured format for outside scripts to use. For example, if I call a command that produces a file and returns a Path, it’d be nice to output to JSON have the outside script parse the JSON to make use of that information.

**Comment by terpstra** [comment]
Unfortunately, JSON can't represent all the value types used by wake. However, wake does have a JSON data model and can pretty print it. Therefore, if you want this, you could transform your output type into a JValue and ```prettyJSON | println``` it.

**Comment by richardxia** [comment]
That seems like it would work. If we end up using that pattern frequently, it'd be nice to add that to a README.
