### ISSUE TITLE
tutorial example error in linkO phase

### ISSUE THREAD

**Issue by davidmlw** [sifive/wake#183]
mkdir .build/12455/.: File exists
BadPath (Error "Non-zero exit status (1) for JSON runner /usr/lib/wake/preload-wake on .build/12450.14.in.json" Nil)

See: https://github.com/sifive/example-c-wake
this example works in dock environment, but met message as above in linux container environment.

**Comment by terpstra** [comment]
I've also cherry-picked this bugfix for inclusion into the bugfix release v0.15.1.
