### ISSUE TITLE
Installing wake in $HOME/bin

### ISSUE THREAD

**Issue by vmurali** [sifive/wake#186]
I tried to install wake in $HOME/bin

I tried
```
./bin/wake 'install "$HOME/bin/bin"'
```

That created a local $HOME. That is not what I want :)

I tried ~ and it "aborted" for whatever reason

**Comment by samh-sifive** [comment]
`~` and `$HOME` are shell constructs and, because the command is enclosed in `' '` the shell will not interpret them.

Note:
```
% echo '"$HOME"'
"$HOME"

% echo "'$HOME'"
'/home/samh'
```

Try instead:
`./bin/wake "install '$HOME/bin/bin'"`

**Comment by terpstra** [comment]
Omg. I just tried `./bin/wake 'install "~/foo"'`. It created a directory called '~' in the wake folder. I *almost* typed `rf -rf ~` to get rid of it... but stopped myself just in time.

**Comment by terpstra** [comment]
Anyway, I briefly toyed with the idea of adding '~/...' to wake paths, but then realized it would introduce the requirement for escapes in paths to make a directory called '~' if that's what you really wanted. So ... wontfix.

**Comment by terpstra** [comment]
If you don't want to use shell escapes as @samh-sifive suggested, you could also write `./bin/wake 'install "{getenv "HOME"}/wherever"'`

**Comment by vmurali** [comment]
OK the two alternatives are both sufficient.

You can change the installation instructions to specify these alternatives, as I would imagine most people wouldn't want to install something in /usr/local
