### ISSUE TITLE
utf8proc gmp re2 ubuntu package does not have pkg-config files

### ISSUE THREAD

**Issue by davidmlw** [sifive/wake#197]
$: WAKE_PATH=/usr/bin  ./bin/wake -v all default                                                 {ed2412d}<mkdir> -m 0775 lib
<mkdir> -m 0775 bin
/usr/bin/git describe --tags --dirty
/usr/bin/pkg-config --short-errors --modversion utf8proc
/usr/bin/pkg-config --short-errors --modversion gmp
/usr/bin/pkg-config --short-errors --modversion re2
<mkdir> -m 0775 lib/wake
No package 'utf8proc' found
No package 'gmp' found
No package 're2' found

**Comment by davidmlw** [comment]
similar happens in ArchLinux, only difference re2 works in ArchLinux.

$ ./bin/wake -v all default
<mkdir> -m 0775 lib
<mkdir> -m 0775 bin
/usr/bin/git describe --tags --dirty
/usr/bin/pkg-config --short-errors --modversion utf8proc
/usr/bin/pkg-config --short-errors --modversion gmp
<mkdir> -m 0775 lib/wake
Package 'utf8proc', required by 'virtual:world', not found
Package 'gmp', required by 'virtual:world', not found

**Comment by terpstra** [comment]
The build still succeeds, though, right?

It is supposed to fallback to a reasonable guess if the pkg-config files are missing.

**Comment by terpstra** [comment]
Problem turned out to be a missing "USE_FUSE_WAKE=0" in the bootstrap build of wake in a container.

**Comment by saurabhsingh-pvips** [comment]
This hasn't been fixed yet. I still get these warnings on stderr even after using 'USE_FUSE_WAKE=0".

**Comment by richardxia** [comment]
@saurabhsingh-pvips, can you describe which version of wake you are using, what your OS distribution and version is, and the steps to reproduce? I am not seeing this behavior on the Wake 0.17 branch. Note that passing the `-v` flag, as in the original comment of this issue, will cause warnings from pkgconfig to propagate to Wake's stderr. If you leave off the `-v`, it should not print the pkg-config errors.

**Comment by saurabhsingh-pvips** [comment]
I've encountered these warnings when downgrading from `v.0.18.x` to `v.0.15.0`. Are these just warnings or these external dependencies may create issues later on usage?

OS Info:
`NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic`

**Comment by richardxia** [comment]
These warnings can be ignored, and they do not show up if you do not set the `-v` flag.
