### ISSUE TITLE
Race condition in `relink_shadow_tree`

### ISSUE THREAD

**Issue by richardxia** [sifive/wake#207]
I forgot the exact details, but I believe there's a race condition that exists in the shadow tree code where two parallel jobs may attempt to write to the same file twice, causing them to hit the error condition described here and abort:

https://github.com/sifive/wake/blob/0d63f30d5b9c6a3d0e24d87d7ee8eba8c2e71265/preload/wrap.cpp#L222-L229

Although it's not good for two jobs to write to the same file, wake should not be hitting a fatal error at this level of the code.

**Comment by terpstra** [comment]
The race is between lines 224 and 225. Two parallel jobs might both try to link the file in 225 at the same time.
