### ISSUE TITLE
build error (or warning)

### ISSUE THREAD

**Issue by sequencer** [sifive/wake#242]
I'm trying to package wake in Arch Linux,
built success with a red warning,
```
WAKE_PATH=/usr/bin ./bin/wake all default
Package 'utf8proc', required by 'virtual:world', not found
Package 'gmp', required by 'virtual:world', not found
Pass "BUILT"
```
seem successfully generate a `elf` file, and `ldd` is clean , but I think this warning cannot be ignored.
I have installed `community/libutf8proc 2.4.0` and `core/gmp 6.1.2`.
any ideas for this issue?

**Comment by terpstra** [comment]
Those warnings are fine to ignore. pkg-config did not find those packages, but the build scripts found them another way.

I should probably silence the warnings, as this question has come up before.

**Comment by sequencer** [comment]
Got it thank you;)
