### ISSUE TITLE
wake installation issue in Ubuntu 19.04

### ISSUE THREAD

**Issue by ShraddhaDevaiya** [sifive/wake#246]
when we fire the command ./bin/wake "install '{getenv "HOME" | getOrElse ""}/$HOME/bin'"
or 
./bin/wake "install '$HOME/bin'"
it gives pass INSTALLED.
but when run the command wake --init it gives:
Command 'wake' not found, did you mean:

  command 'rake' from snap ruby (2.6.3)
  command 'jake' from deb node-jake (0.7.9-1)
  command 'make' from deb make (4.2.1-1.2)
  command 'make' from deb make-guile (4.2.1-1.2)
  command 'rake' from deb rake (12.3.1-3)
  command 'fake' from deb fake (1.1.11-3)
  command 'cake' from deb cakephp-scripts (2.10.11-2)

See 'snap info <snapname>' for additional versions.

**Comment by terpstra** [comment]
You just need to run it from where you installed it ...
```
~/bin/wake
```
... or install it somewhere else.

**Comment by ShraddhaDevaiya** [comment]
that's what I am saying, it is not properly installed by given command, I have tried once again but it gives command not found. so can you just give us , some another command to install it?

**Comment by richardxia** [comment]
> that's what I am saying, it is not properly installed by given command, I have tried once again but it gives command not found. so can you just give us , some another command to install it?

`./bin/wake install` will install wake wherever you tell it to install to. Your problem is that you haven't added that directory to your PATH environment variable. See http://www.linfo.org/path_env_var.html for more info on how the PATH environment variable works.

**Comment by ShraddhaDevaiya** [comment]
Okay, thanks ! it is working now.
