### ISSUE TITLE
Deleted version controlled files become BadPath when found via sources

### ISSUE THREAD

**Issue by jackkoenig** [sifive/wake#273]
Not sure if this should or shouldn't be an error, but the error message could mention that it's a deleted version-controlled file instead of just "source does not exist".

**Comment by terpstra** [comment]
When you first reported this to me, I though it was including these files into the output of 'sources' (plural) as a BadPath. My testing indicates this only happens for 'source "file.cpp"', where I think this error is correct.

**Comment by jackkoenig** [comment]
It still occurs for `sources`. One could argue this is correct and that you need to do a `git rm`, thoughts?
```
jack@Jacks-MacBook-Pro:~/work/wake$ wake --version
wake v0.17.0-alpha-93-g8396d8b
jack@Jacks-MacBook-Pro:~/work/wake$ wake 'sources here `.*\.jack`'
Nil
jack@Jacks-MacBook-Pro:~/work/wake$ echo "hi" > file.jack
jack@Jacks-MacBook-Pro:~/work/wake$ git add file.jack
jack@Jacks-MacBook-Pro:~/work/wake$ git commit -m "add file.jack"
[master 9a0c81f] add file.jack
 1 file changed, 1 insertion(+)
 create mode 100644 file.jack
jack@Jacks-MacBook-Pro:~/work/wake$ wake 'sources here `.*\.jack`'                                                                                                               
Path "file.jack", Nil
jack@Jacks-MacBook-Pro:~/work/wake$ rm file.jack
remove file.jack? y
jack@Jacks-MacBook-Pro:~/work/wake$ wake 'sources here `.*\.jack`'
BadPath (Error "file.jack: source does not exist" Nil), Nil
```

**Comment by terpstra** [comment]
Ahhhh! I thought the issue was if you did a 'git rm', not an 'rm'.

**Comment by terpstra** [comment]
So, what should it do?
1- Report it as a legal Path (even though it does not exist)
2- Omit it from the List
3- Report it as BadPath (current behaviour)
4- Something else?

**Comment by terpstra** [comment]
From a reproducibility stand-point, I think I actually like the current behaviour.

**Comment by jackkoenig** [comment]
Yeah you're probably right. Just like a file must be `git add`ed to be seen, it should be `git rm`ed to be gone. With this in mind, it makes sense that you'd get a BadPath if you just deleted it

**Comment by terpstra** [comment]
Ok. Closing this as 'wontfix'.
