### ISSUE TITLE
Wake shell scripts (-s) should use the real runner

### ISSUE THREAD

**Issue by jackkoenig** [sifive/wake#277]
If I'm trying to debug a sandboxed job, it'd be really useful if I could create that sandbox easily. As such it would be really nice if `-s` would give me the `fuse-wake` invocation (including the JSON).

Furthermore, it would be awesome if `fuse-wake` had an `--interactive` mode that would create the sandbox, but not yet invoke the job so that one can manually inspect the filesystem.
Then after pressing `Enter` would run the job but pause after it's finished so that the filesystem can manually inspected again.
A final `Enter` would let `fuse-wake` teardown the sandbox and exit.

Per our offline conversation, the runner and JSON are not currently stored in the database, so this is probably non-trivial to implement.

**Comment by jackkoenig** [comment]
I actually don't think this should be the default `-s`, I think it's good to hide these things from normal users who might want to use `-s`, but some kind of `--super-debug-give-me-script` for people writing Wake rules would be great.

**Comment by terpstra** [comment]
The tricky part here is that the database does not actually record how the Job was run, only what the runner should have done.

**Comment by terpstra** [comment]
So, based on the plan of record for sandboxes and runners going forward, wake should not do this.
Instead, it should indicate the required sandbox, and you should be able to run the slurm-runner or the aws-runner or whatever on the script from wake.
