### ISSUE TITLE
`wake -g symbol` to show the symbol information

### ISSUE THREAD

**Issue by davidmlw** [sifive/wake#279]
It would be useful to check a symbol's definition.
`wake -g` gives a whole list but too much. 
it would be wonderful to have `wake -g symbol` or `wake info symbole` to show the symbol's information and file and line.

**Comment by terpstra** [comment]
I think 'wake -v symbol' does this. Can you confirm this meets your needs?

**Comment by davidmlw** [comment]
Yes, this is what I mean!
