### ISSUE TITLE
Segmentation fault : Tutorial

### ISSUE THREAD

**Issue by ultragamza** [sifive/wake#282]
I got a "Segmentation fault" problem with the first step of the wake tutorial.

Here is my command line history:
- playground# mkdir tutorial
- playground# cd tutorial
- playground/tutorial# wake --init .
- playground/tutorial# wake '5 + 6'
- 11
- /playground/tutorial# wake -v '5 + 6'
- Segmentation fault (core dumped)

Environment:
- Ubuntu 16.04.6 LTS
- Docker version 18.09.6
- git version 2.17.1
- wake version "0.17.0~alpha.42+g2dba999"

Thanks in advance for your help.

**Comment by terpstra** [comment]
Please use v0.16. The master branch is in the middle of a big transition such that I'm not surprised it is unstable.
