### ISSUE TITLE
How does wake orchestrate builds across multiple machines?

### ISSUE THREAD

**Issue by starfivetech** [sifive/wake#291]
1. Suppose two wake workspace A and B, and A depends on B's output. How A and B collaborate in Wake script or command?

2. What if A and B reside in two machines that are connected throught ssh or orther job system?

**Comment by terpstra** [comment]
While it possible for wake to run remote jobs (via ssh or whatever), the wake model is that there is a single workspace that holds the results of all the jobs (remote or local). ie: wake does not support multiple workspaces.

**Comment by sifan-china** [comment]
For a remote job's outpub, for example ssh job, how Wake monior the output files, is there some other setup for the environment?

**Comment by terpstra** [comment]
You can run the 'fuse-wake' runner also remotely. So, the general strategy is that you add a custom runner that works as follows:
- accepts a JSON file from wake describing the job
- copies or shares the files listed in that JSON to the remote host
- on the remote host hands the JSON file the the 'fuse-wake' runner executable
- copy or share all the files in the produced files back to the source machine
- report the created JSON file back to wake
