### ISSUE TITLE
Pipe with two commands

### ISSUE THREAD

**Issue by i4kimura** [sifive/wake#322]
I'm a beginner of Wake and making a building environment using wake.
I want to realize two commands connection with pipe like : `command1 | command2`

In wake 
```
global def test _ =
  def cmd1 = "gen_pattern", Nil
  def cmd2 = "tail", "-n", "100", Nil
  def plan = makePlan cmd1 Nil
    | setPlanEnvironment(Nil)
        | runJob
        | getJobStdout
        | getWhenFail "Fail"
  println plan
```

How to connect cmd1 and cmd2? Should I make two separate def rule?

**Comment by terpstra** [comment]
There are two ways to solve this. The most direct way to achieve what you're asking for:
```
def cmd = shellPlan "%
  gen_pattern | tail -n 100
  %" Nil
def job =
  cmd
  | setPlanEnvironment Nil
  | runJob
plan
| getJobStdout
| getWhenFail "Fail"
| print
```
The above will run the embedded shell script as a the Job instead of each command separately.

However, if you actually want to log the entire output of stdout into the database, you can just run cmd1 and then selectively print only the last 100 lines.
```
def cmd1 = "gen_pattern", Nil
def job =
  makePlan cmd1 Nil
  | setPlanEnvironment Nil
  | setPlanStdout logVerbose
  | runJob
job
| getJobStdout
| getWhenFail "Fail"
| print
```

**Comment by msyksphinz** [comment]
Thank you for your reply. I searched `shellPlan` in wake but not defined.
How to define shellPlan? `makePlan` separates command and arguments, but I couldn't find how to realize `shellPlan`.

**Comment by terpstra** [comment]
What version are you using? shellPlan was introduced in v0.16.0.

**Comment by msyksphinz** [comment]
Oops my wake version is 0.15. I will use latest version.
