### ISSUE TITLE
Executing programs in wake

### ISSUE THREAD

**Issue by i4kimura** [sifive/wake#323]
When I execute external program, how to specify it?

I understand wake make new directory and move building directory from original position, so external program path should be absolute.

```
global def test2 _ =
  def cmd1 = "./external_program", Nil
  def plan = makePlan cmd1 Nil
    | setPlanEnvironment(Nil)
    | runJob
    | getJobStdout
    | getWhenFail "Fail"
  println plan
```
`./external_program` locates same as wake file. When wake execute, wake create new directory and move it, so generate error that : `./external_program file is not found.`.
How to specify path of external program?

**Comment by terpstra** [comment]
Your use of "./" seems to contradict your use of the word "external", so I'll explain three cases.

1. The program you want to run is not inside your project workspace. It has some path like /usr/bin/external_prgram. In this case, you just specify "/usr/bin/external_prgram".

2. The program you want to run is a source file inside the workspace; ie: it's checked in to the git repository. In this case, you need to do this:
```
def prog = source here "git-source-program"
def myJob =
  makePlan (prog.getPathName, "arg1", Nil) (prog, Nil)
  | runJob
  | ...
```

The key point here is that you need to pass "git-source-program" to the second argument of makePlan which specifies which files are visible to the Job. This is necessary for remote execution and sand-boxing.

3. The program you want to run was built by some other Job
```
def program = someOtherJob.getJobOutput
def myJob = makePlan (prog.getPathName, "arg1", Nil) (prog, Nil)
  | runJob
  | ...
```

Here, you need to feed the output of the earlier build step that creates the executable to the following Job which consumes/runs it.

**Comment by msyksphinz** [comment]
Thank you for your reply. In my case 2. I will try `prog.getPathName`.

**Comment by terpstra** [comment]
I'm reopening this issue as an FAQ item.
