### ISSUE TITLE
Tutorial pattern matching with default one is giving an error!

### ISSUE THREAD

**Issue by ShraddhaDevaiya** [sifive/wake#339]
Following is the code which I have written in the .wake file:
```
global data Animal =   
  Cat (name: String)
  Dog (age: Integer)

global def strAnimal a = match a
  Cat x = "a cat called {x}"
  Dog y = "a {str y}-year-old dog"

global def matchWithDefault a = match a
  Cat x = "a cat called {x}"
  _     = "not a cat!"
```
for this whenever I am giving the following command ,
```
$wake 'matchWithDefault ( )'
```
it is giving me an error like this :
```
  Was expecting an (OPERATOR/LAMBDA/ID/LITERAL/PRIM/POPEN), got a PCLOSE at <command-line>:1:20
Type error; function <command-line>:1:[1-16] expected argument 'a' of type:
    Animal
  but was supplied argument <command-line>:1:[18-20] of type:
    String
>>> Aborting without execution <<<
```
So, how can I run this default one for pattern matching in wake?

**Comment by richardxia** [comment]
Hi @ShraddhaDevaiya, could you please edit your code examples to use Markdown-formatted code blocks? Whitespace is significant in Wake, so it is difficult to determine what the issue is if we cannot see the proper indentation of your code examples. See https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks for more information.

Also, it would be helpful to list the exact version of Wake that you are using, as the language is still undergoing rapid development.

**Comment by ShraddhaDevaiya** [comment]
Yeah, sure. here it is:
global data Animal =   
  Cat (name: String)
  Dog (age: Integer)
 
global def strAnimal a = match a
  Cat x = "a cat called {x}"
  Dog y = "a {str y}-year-old dog"

global def matchWithDefault a = match a
  Cat x = "a cat called {x}"
  _     = "not a cat!"   
wake version is v0.16.0-alpha, means i have checked out this version.

**Comment by richardxia** [comment]
Hi @ShraddhaDevaiya, the formatting still isn't coming out right. You need to surround your code example with triple backticks both above and below. You can preview your message before posting it to check if it is being formatted correctly.

I looked at your original message a little bit closer, and I realized that you wrote that you were trying to run the following command:

```sh
$ wake 'matchWithDefault ( )'
```

It is not valid to have an empty set of parentheses in Wake. Note that the parentheses are not the same as a function call in most other languages. Wake is inspired by the [ML](https://en.wikipedia.org/wiki/ML_(programming_language)) family of languages, such as OCaml, and the syntax for function calls in that language is to just separate the function name and its arguments with whitespace.

On a side note, you should probably switch to a stable release of Wake. The `-alpha` releases not guaranteed to be stable, and it is possible that they could have major bugs in them.

**Comment by ShraddhaDevaiya** [comment]
okay, let me try with stable release . and sorry for giving you again unformatted code. next time onwards will take are of it. and instead of wake  'wake 'matchWithDefault ( )' what can we write to check whether the default value is coming or not?

**Comment by jackkoenig** [comment]
Hi @ShraddhaDevaiya, I've edited your original question to add triple backticks around the parts that need it. @richardxia has pointed out the issue, it is in fact your command-line argument `wake 'matchWithDefault ( )` that is the issue.

Try passing an Animal to see:
```
$ wake 'matchWithDefault (Cat "Barry")'
"a cat called Barry"
```
You can also just pass the name of the function:
```
$ wake 'matchWithDefault'
<test.wake:11:[12-29]>, AN UNEVALUATED FUNCTION
```
Or use `-v` to see the type of the function (and other verbose options):
```
$ wake -v 'matchWithDefault'               
matchWithDefault: (a: Animal) => String = <test.wake:11:[12-29]>, AN UNEVALUATED FUNCTION
```

**Comment by ShraddhaDevaiya** [comment]
Yeah, but here also , as we can see it is giving an error like,
An unevaluated function so this is the output or  it should give some default message which is:
"not a cat !"  
so what is it?

**Comment by jackkoenig** [comment]
`AN UNEVALUATED FUNCTION` isn't an error (although I agree the red text make it seem so).
It's just reporting that you're passing a function instead of an evaluated function.

Note that `$ wake 'matchWithDefault (Cat "Barry")'` just prints the value, but `$ wake 'matchWithDefault'` where I'm just passing the name of the function (and no argument) is the one that reports `AN UNEVALUATED FUNCTION`, because it _is_ an unevaluated function!

**Comment by ShraddhaDevaiya** [comment]
Okay, understood. But here, my concern is , how will it match with default value or will take default value instead of giving this message?

**Comment by richardxia** [comment]
Wake doesn't have the concept of a default value. Depending on your use case, the best approximation may be to pass in an `Option` type, which represents a value that may or may not be present. You can think of it as a way of having a type-safe `null` in the language. If you use the `getOrElse` function, you can provide a default value in the case where the Option has a value of `None`.

See https://github.com/sifive/wake/blob/9880d08d7dba925e0d31ea98fa00b1145edfd8bd/share/doc/wake/tutorial.md#option for an example, and https://en.wikipedia.org/wiki/Option_type for more details on the programming concept in general.

**Comment by ShraddhaDevaiya** [comment]
Okay thanks for helping out ! will go through it .

**Comment by terpstra** [comment]
Actually, the recommended wake style for situations where you would like function arguments with default arguments is to accept a tuple instead of direct arguments. See the excellent article here: https://github.com/sifive/wake/blob/master/share/doc/wake/tour/tuples.adoc
