### ISSUE TITLE
Change default branch on Github to latest stable branch

### ISSUE THREAD

**Issue by jackkoenig** [sifive/wake#342]
Quite frequently, we get error reports because people use wake from master (eg. https://github.com/sifive/api-scala-sifive/issues/18). One way to prevent such confusion is to change the default branch on Github to be the latest stable branch, see https://github.com/sifive/wit where the default branch is currently 0.11.x

**Comment by terpstra** [comment]
I don't know how to do this. When I look into the github settings, it says I can change the default branch, but then all PRs are made against that branch, which is not what I think you are requesting.

**Comment by jackkoenig** [comment]
Changing the default branch also changes the default branch you make PRs against, I wish you could do one without the other but I don't think that's supported. It's a bit annoying to have to change the default branch whenever you make PRs, but it goes a long way toward preventing other people from accidentally just building from master (which has come up so many times)

**Comment by terpstra** [comment]
Alternatively, I could just stop breaking master. ;)

**Comment by jackkoenig** [comment]
Easier said than done 🙂

**Comment by terpstra** [comment]
I think this is not really an issue any more, because people are using the release versions, not the git repository. Also, there is a versioned API that does not break between updates.
