### ISSUE TITLE
Feature Request: More clear Exit status

### ISSUE THREAD

**Issue by mwachs5** [sifive/wake#343]
Wake Version Using: 15

It would be nice if there was a very clear PASS or FAIL or EXIT CODE as the **very last** thing printed when a wake run fails. Right now it seems to print the last failing command (not sure what happens when it succeeds, haven't gotten there yet), then you can scroll up to see what happened. But it's not that obvious when coming to a build that has exited, whether it succeeded or not, since that last command may be more than a screen's worth of text long and shows up white either way,

**Comment by terpstra** [comment]
Wake DOES print Pass/Fail as the very last thing (and exit with a corresponding exit status of 0 or 1). However, your target expression needs to return a 'Result' for this to work. Does it?

**Comment by terpstra** [comment]
Unless you can provide more detail, I'm going to close this issue, as I believe what you are asking for already, in fact, exists.
