### ISSUE TITLE
Wake core dumps if run from a directory that no longer exists

### ISSUE THREAD

**Issue by richardxia** [sifive/wake#344]
This was on wake 0.17.1.

Steps to reproduce:

```sh
$ mkdir workspace
$ cd workspace
$ wake --init .
$ mkdir child_dir
$ cd child_dir
$ wake '1 + 1'
2
$ (cd .. && rm -rf child_dir)  # Remove the current directory from a subcommand
$ wake '1 + 1'
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_replace
Aborted (core dumped)
```

**Comment by terpstra** [comment]
Interestingly, that test passes on mac OS.
```
terpstra@peach:~/foo$ wake --version
wake 0.17.1
terpstra@peach:~/foo$ wake '1+1'
2
terpstra@peach:~/foo$ (cd ..; rm -rf foo)
terpstra@peach:~/foo$ wake '1+1'
Unable to locate wake.db in any parent directory.
```

Fortunately, debugging on Linux is easier.

**Comment by terpstra** [comment]
On linux, getcwd fails with errno=ENOENT. On MacOS, getcwd succeeds with the path as though it still existed. According to <https://pubs.opengroup.org/onlinepubs/9699919799/functions/getcwd.html>, linux is not doing the right thing (TM). However, working around this issue is easy enough.

**Comment by richardxia** [comment]
Thanks for fixing it!
