### ISSUE TITLE
Can Wake support local publishing?

### ISSUE THREAD

**Issue by davidmlw** [sifive/wake#350]
Thhere always some cases that need `rm -rf build/*` to rebuild the workspace, while chisel/firrtl, and for most users, rocket-chip, are not neccessory to rebuild the jar from source code. 

Is that possible that set up an env variable directory in environment-wake, that wake can publish the compiled ScalaModule in a local file directory with the git hash code. And wake will use the local publish first, otherwise compile a fresh one in build/.

It would be better if the sbt users can use the local published jar files.

**Comment by richardxia** [comment]
This is more of an api-scala-sifive issue than a Wake issue, and it looks like you've already filed as a ticket in https://github.com/sifive/api-scala-sifive/issues/16.

Sorry for taking a while to get to it, but I believe that this and incremental recompilation are high on @jackkoenig's priority last, which he will hopefully have a bit of time to spend on when he's back from vacation in a couple weeks.

**Comment by terpstra** [comment]
Actually, this is exactly what shared caching is supposed to address. At some point I will enable this feature for wake, but it carries risk so long as our builds do not pass "wake -c" cleanly.

**Comment by terpstra** [comment]
That said, the fact that you need to blow away build/ suggests that shared caching would not have been safe in your build.
