### ISSUE TITLE
Feature Request: more logging helpers

### ISSUE THREAD

**Issue by albertchen-sifive** [sifive/wake#351]
https://github.com/sifive/environment-example-sifive/pull/3#pullrequestreview-343687625

I like @richardxia's suggestion of having logging functions that take a prefix function. maybe have a version that defaults to prefixing with the package name when we get namespaces?

Also nice would be the ability to truncate logs lines to fit the terminal window like how wake does when it shows the currently running command.

The ability to print different colors would be really nice too.

**Comment by terpstra** [comment]
Red is not enough for you?
