### ISSUE TITLE
Code comments on all 'global' symbols

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#353]
As reading the source at https://sifive.github.io/wake/ is one of the primary methods of discovering and understanding the functionality of wake, it would be helpful if all the global functions/types were explained inline in the code. Much of it does have this already but there is plenty of gaps, for example: sources.wake, cp.wake, gcc.wake

**Comment by sistillson** [comment]
+1

**Comment by sistillson** [comment]
whoops

**Comment by mmjconolly** [comment]
Copying the text of https://sifive.github.io/wake/ into Untitled.txt to preserve the formatting of the page, we can get some rough numbers
```
$ cat Untitled.txt | grep 'global def' | wc -l
     444
$ cat Untitled.txt| grep 'global def' -B 1 | grep '#' | wc -l
     253
```

**Comment by terpstra** [comment]
Pull requests accepted!

**Comment by terpstra** [comment]
Done.
