### ISSUE TITLE
Ignore some wake files

### ISSUE THREAD

**Issue by terpstra** [sifive/wake#355]
In some cases, you can end up with wake files in a workspace that should be ignored.

Use cases:
- unit tests for wake itself
- submodules in repositories only half transitioned to wit

There are some related improvements that will reduce this need:
- use namespaces (avoids symbol conflicts)
- multiple concurrent wake processes sharing the same database

However, the above examples illustrate this feature should probably exist.

**Comment by mmjconolly** [comment]
Hi @terpstra 
How do you feel if we had a `.wakeignore` file with regex patterns much like how git has `.gitignore`?
The use case I'm looking at is trying to transition some submodules of a wit dependency into wit, and am running into duplicate symbol definitions.
```
workspace
├── repo1
│   └── foo.wake
└── repo2
    └── repo1
        └── foo.wake
```
I want to be able to run `wake` from `workspace`, but also run `make` from `repo2`, with it's submodules initialized.
In this example the `.wakeignore` would be in `repo2` with the contents `repo1/*`
