### ISSUE TITLE
Revise Runner API to allow arbitrary stacking

### ISSUE THREAD

**Issue by terpstra** [sifive/wake#356]
The current Runner API requires a new runner to be built on top of exactly one other Runner. This is a problem, because some Runners would like to modify the environment regardless of which next Runner takes over execution. Probably the API should be changed such that after a Runner transforms the RunnerInput, the updated Plan is re-scored and matched against another Runner, until it is finally consumed by the localRunner.

**Comment by mmjconolly** [comment]
wont fix, change of model
