### ISSUE TITLE
Target subkey mismatch

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#385]
When looking at an error like:
```
ERROR: Target subkey mismatch for ./some/path/foo.wake:7:[1-100]
To debug, rerun your wake command with these additional options:
  --debug-target=1 to see the unique target arguments (before the '\')
  --debug-target=2 to see the first invocation's extra arguments
  --debug-target=3 to see the second invocation's extra arguments
```
I don't feel there is enough information to understand what is going on without running the `--debug-target` bits

`Target subkey mismatch` describes the problem in terms of the wake internals which the user wont know (what is a subkey? why would it mismatch?). Please describe the issue in vocabulary that the user would have

Additionally, there is probably useful information in the `--debug-target` ids that is worth printing out here without asking the user to copy/paste to discover.

**Comment by terpstra** [comment]
Yeah. This is hard to fix, which is why it still works this way.

There are two problems:
- I think the whole concept of subkeys is flawed, and I have plans to rework this in 0.19
- At the point the error is detected, I only have hashes; the original information is gone. That's why it asks you to rerun with a supplied hash. It then reports the information when the hash function creates the specified hash. A total hack, but better than the previous situation where you had no visibility.

**Comment by mmjconolly** [comment]
What is the information that is needed that is lost, can it be stored in the sqlite database?

**Comment by terpstra** [comment]
The right fix here is to make this error impossible. I have a plan; I just need some time to execute it.

**Comment by davidmlw** [comment]
Are there some progresses of this issue. I met this problem, but rerunning with `--debug-target` provides no further informaiton and help.

**Comment by terpstra** [comment]
There is a plan, but it has not been implemented yet. If you ran `wake -x "do whatever"` and it fails with a subkey mismatch, you should rerun with `wake --debug-target=HASH -x "do whatever"`. Then it should report what the conflict was. Does this not work?

**Comment by davidmlw** [comment]
Aha, it helps.

**Comment by terpstra** [comment]
FYI, I no longer believe that this problem can be made to "go away". It was thinking about overly simplified build systems ala "wake as a library" discussions we were having at the time that made me think this was possible to eliminate.

Fortunately, I think we can provide much better diagnostics now.
