### ISSUE TITLE
Document JSON functions.

### ISSUE THREAD

**Issue by richardxia** [sifive/wake#391]
There are zero comments in https://github.com/sifive/wake/blob/eee399fe4841e0390a871abefb823b736c01eef6/share/wake/lib/core/json.wake, and it is not obvious to me what the `/|`, `/../`, `//`, and `==/` functions do without having to read a lot of similarly undocumented helper functions like `jfilter` and `jfind`. It's also not obvious which operations are recursive and which are not; from its name, I would have expected `jfilter` to be recursive, but it does not appear to do that.

At the very least I think we need a short comment at the top of each of these functions that describes in plain, English prose what the function does. Even better would be to add a document to the Tour describing the JSON operations in detail.

**Comment by albertchen-sifive** [comment]
also, the json functions sometimes behave weirdly, because they all return `JArray` and use it like an option type. like these two expressions return the same thing.
```
$ wake -x 'JObject ("asdf" → JString "asdf", Nil) // `asdf`'
JArray (JString "asdf", Nil)
$ wake -x 'JArray (JObject ("asdf" → JString "asdf", Nil), Nil) // `asdf`'
JArray (JString "asdf", Nil)
```

which leads to unintuitive behavior when combining with stuff like `/../`
```
$ wake -x 'JArray (JObject ("asdf" → JString "asdf", Nil), Nil) /../ (_ // `asdf` ==/ JString "asdf")'
JArray (JArray (JObject (Pair "asdf" (JString "asdf"), Nil), Nil), JObject (Pair "asdf" (JString "asdf"), Nil), Nil)
```

like for the above I would have expected just a single element in the resulting `JArray`. This also means that the `getJ*` functions all have to succeed on both `JArray (jvalue, Nil)` and `jvalue`. I think ideally these json operators would all return a `Result` type.

or change them so that they don't wrap results in `JArray`? like `//` only works on `JObject` and returns `JNull` otherwise. and `/|` only works on `JArray` and returns `JNull` otherwise? And then the `getJ*` dont have to match on `JArray (thing, Null)`.

**Comment by terpstra** [comment]
Since you guys did not end up using these functions. I was planning on not including them in 1.0.

**Comment by terpstra** [comment]
I was trying to make it possible to write jquery-style expressions. I am open to a better more wake-friendly API.

**Comment by richardxia** [comment]
I thought we are using some of these functions. @albertchen-sifive would know the best, since I think he's used (or attempted to use) them the most.

> I was trying to make it possible to write jquery-style expressions. I am open to a better more wake-friendly API.

Did you mean XPath-style, not jQuery? These do not look like jQuery expressions to me, and jQuery expressions really rely on having the notion of a `class` or other label/identifier that can be attached to any Element (i.e. any `<foo>` tag in HTML/XML).

In Wake's JSON API, it's not clear to me whether all `JValue`s are considered "elements" in an analogous sense to jQuery or if only `JObject`s are considered "elements". There is a fundamental difference between the XML model and the JSON model, and that affects querying libraries.

**Comment by richardxia** [comment]
One more thought that popped into my head: Both XPath and jQuery operate on XML-like structures, and both query languages benefit from that because there is a very natural and consistent recursive structure where everything is "node" and "children", where nodes may additionally have attributes.

With JSON, it's less clear whether a recursive visitor should visit each JObject or each JValue.

**Comment by terpstra** [comment]
Indeed. Perhaps a better AST would have been:

```
export data JNode =
  JLeaf JLeaf
  JObject  (List (Pair String JNode))
  JArray   (List JNode)
export data JLeaf =
  JString  String
  JInteger Integer
  JDouble  Double
  JBoolean Boolean
```

**Comment by colinschmidt** [comment]
Eventually https://github.com/sifive/wake-extras/blob/main/json.wake this will be migrated into this repo and replace the current JSON library.
