### ISSUE TITLE
HTML markup of targets sometimes has incorrect type annotation

### ISSUE THREAD

**Issue by richardxia** [sifive/wake#392]
<img width="465" alt="Screen Shot 2020-03-31 at 2 36 02 PM" src="https://user-images.githubusercontent.com/1002748/78077323-0918e280-735d-11ea-8ef5-85519eeb5cff.png">

I've noticed that for some, but not all, `target`s, when you hover over the function name, it shows the type as `Target` instead of the actual type signature of the function arguments and return value. The screenshot above is from the latest version of the HTML annotated source for the [`whichIn`](https://github.com/sifive/wake/blob/eee399fe4841e0390a871abefb823b736c01eef6/share/wake/lib/system/path.wake#L98) function as published on GitHub (eee399fe4841e0390a871abefb823b736c01eef6 as of the time of this writing).

**Comment by terpstra** [comment]
lol. You are stealing wake's secrets!

**Comment by richardxia** [comment]
Shouldn't have made the HTML annotations display them then 😛
