### ISSUE TITLE
Should wake loose the bind with git?

### ISSUE THREAD

**Issue by davidmlw** [sifive/wake#409]
Current wake sources have to be git versioned files, while this is not true for most of build case. Suppose a tar ball is downloaded with wake script, it shoule just work when open the box.

https://github.com/xmake-io/xmake xmake is a tools popular now for some Chinese community. I am considering write a wake version of xmake, when I have spare time.

**Comment by terpstra** [comment]
This is not correct. Wake interprets all .wake files in the workspace that are not excluded by the .wakeignore. However, it is true that wake currently only supports 'source "file"' for things either listed in git, or in a manifest.wake/etc that does a 'publish sources = ...'.

**Comment by terpstra** [comment]
Speaking of a build from a tarball, consider downloading a wake release and trying it for yourself: https://github.com/sifive/wake/releases/download/v0.18.0/wake_0.18.0.tar.xz

**Comment by terpstra** [comment]
You will note that the tarball contains a file 'manifest.wake' which primes the list of source files in the  released tarball (since there is no git).

**Comment by terpstra** [comment]
Oh, one last note "Suppose a tar ball is downloaded with wake script". In that case, the download step creates an output "the tarball" and then when you untar the tarball, that creates outputs for the contents. That gets you the files to pass forward to the dependent jobs.
