### ISSUE TITLE
Switch to GitHub Actions?

### ISSUE THREAD

**Issue by richardxia** [sifive/wake#411]
This is Richard promising to take a look at this eventually (before the 0.19.0 release). He is also interested in switching to GitHub Actions, which may simplify the binary artifact uploading step.

**Comment by terpstra** [comment]
I made a small script to download the artefacts myself. Leaving this ticket open for github actions.

BTW, I see that circle CI is using kernel 4.15. Interesting would be to try a CI with kernel >= 4.18 so we can see if fuse works inside docker there.

**Comment by terpstra** [comment]
You don't need to keep this promise. I can switch it over myself, if we decide this is a good idea. I kind of like circleCI for now.
