### ISSUE TITLE
How to explicitly define job dependency by virtual Job outputs or by JobID?

### ISSUE THREAD

**Issue by davidmlw** [sifive/wake#422]
I am trying to use bloop to compile and run scala module. The problem is that the compile command does not generate jar result, but a list of classes. While I think it does not need to generate a real jar, only a virtual hashed file result that indicates the compilation is done. And more over, if the input scala files changed, then the bloop compile will be invoked, if the files have no change, the bloop compile will not be invoked. So the virtual hashed file result should be a function of all the input hashes.

So my plan will be setup a LocalOnly Plan, and the set the input files manually and then call `bloop compile`. And generate a hash code and set it as the job output manually. So we can establish a input/output hash chain. And I think there is no need to write this hash code down to a file, it is just a code in the database.

And a related question, as the compilation acctually happens in the bloop server, Will wake trace the  output files?

**Comment by davidmlw** [comment]
I am obsessed in bloop incremental because it save lots of time and increase the edit-feedback loop. Especially for a begginner of Chisel and Scalar, it helps to learn how his modifications apply to circuits results.

**Comment by davidmlw** [comment]
I try to write a hash file of all input files and let it be "bloop compile" output, while this results in the hash file be a file output by multiple jobs, one is the `write` and one is the `bloop`. So the only way to add a job hash code is to add new API.

Some process I tried:
1. record all the input files of a scala module compile task, use sha1sum to get a stdout hash output,
2. signature aka hash a plan to get a hash code,
3. appending step 2 hash code to step 1 result, and write the content to a file jobhash.
4. manually set the jobhash as the output of bloop compile.

While both step 3 and 4 will generate the jobhash file, and the wake is terminated. So how can job
in step 4 steal the output from step 3?

So currently wake tracks input/output files to get a file hash chain to manage the job dispatching system. But how about a group of jobs that that have no explicit input/output files but still have dependencies, so wake may also need a job hash chian system, and this is generic in another aspective.

I would propose, in Job Outputs, there is a new type of `data` JobID or JobHashCode. And when a Plan's Visibles include a JobID, then the job dependecy is established. That is, a JobID is a kind of Job Outputs but not files. I prefer JobID rather than JobHashCode, because JobID is unique too, and could be used in many cases as we discussed in another thread.

**Comment by jackkoenig** [comment]
I haven't really thought about potential changes to Wake, but I suspect they are not necessary.

I think bloop incremental compile would be awesome, but I think we can get nearly as good of performance using mill with some relatively simple improvements to `api-scala-sifive`.  We just cracked Wit `v0.13.0`, which removed the Scala plugin, and api-scala-sifive `0.2.0`, which now will fetch the Scala stuff. If we forward port the changes in my old branches to [Wit](https://github.com/sifive/wit/tree/mill) and [api-scala-sifive](https://github.com/sifive/api-scala-sifive/tree/mill-incremental-compile), incremental compile will work with mill.

It's not _quite_ as good as the Bloop server, but it's pretty good in my past experiments.

**Comment by davidmlw** [comment]
I think it is useful for Wake to add Job virtual dependency in addition to file dependency. 

For the above example, one can write a wrapper script, run 'bloop compile module' and write down all the input files hash code in to a file, and then Wake will accept the hash file is the output of the compile process. While now, wake has already done all the things, but it is too clever to accept the hash file pretending to be the output.

I also think of another scenario, a lot of EDA tools are heuristic processes, and dont guarentee the same outputs with exacactly same inputs. Maybe we also need a covering scheme to replace the original file hash chain.

**Comment by davidmlw** [comment]
I think I partially solved this problem. Sample code is below, and it needs some further feature to make it better:
1. test a path being a file or a directory
2. hash a path with contents not by the wake path var.
3. it is better for a job to report a hash code for all its inputs/visibles.

`
tuple PlanChain =
  Plan: Plan
  Deps: List PlanChain

global target runPlanChain chain =
  def hash content = prim "hash"
  def input = chain | getPlanChainPlan | getPlanVisible | hashPaths
  def deps = chain | getPlanChainDeps | map runPlanChain | map getPairFirst
  def code = (input, deps) | hash
  chain.getPlanChainPlan
  | editPlanEnvironment ("PLANCHAIN_HASH_HACK={code.format}", _)
  | runJob
  | Pair code

global def makePlanChain plan = PlanChain plan Nil

global target hashPaths paths = match paths
  Nil = 0
  _   =
    def hash content = prim "hash"
    def sorted = paths | sortBy (_.getPathName <* _.getPathName)
    def cmd = "sha1sum", (map (_.getPathName) sorted)
    makePlan cmd paths
    | setPlanEcho Quiet
    | runJob
    | getJobStdout
    | hash
`

**Comment by davidmlw** [comment]
I think the question I am thinking about is how Wake handle outside states. Wake simplies the outside as hash codes.

For some jobs, they may have no outputs, or they have outputs, but we may not track them all. Take 'bloop compile module' as example, the output are the classes, but it doesn't matter what the classes are, Wake only needs to know the compile process is done, and the classes are outside states of Wake. Another example would be a job that update a database, there is no chance for Wake to get the hashcode of a database. Wake also needs simplify this process as a hash code of all its inputs.

**Comment by davidmlw** [comment]
I just think of there is a Wake implementation detail may impact this code snippet: https://github.com/sifive/wake/issues/422#issuecomment-617275299.

Does (Pair code job) has a sync side-effect? Will `runPlanChain` wait both code and job has been generated and compose a Pair when it returns? 
1. If so, then there is a sync side-effect that when I have a code, I have a job done. 
2. If not, (Pair code job) can be partially generated and passed to next level `runPlanChain`, then there is a chance that I have all the codes of the PlanChain, but have none job done.

**Comment by davidmlw** [comment]
I tried your approaches mentioned in https://github.com/sifive/wake/issues/422#issuecomment-617334228. 

I find a way package the output classes to jar like you does. But bloop does not respect `classesDir` now but generates a random dirctory to save the classes, it is difficult to collect the classes now. I am investigating how to get a stable bloop classes output directory.

**Comment by davidmlw** [comment]
I think I have another workaround. Just let Job Status hashed into code, then it can be sure that (Pair code job) is synced.

**Comment by davidmlw** [comment]
I finally get bloop work with ScalaModule, see here, https://github.com/davidmlw/api-scala-sifive/tree/bloopspace.  
1. Use bloop to incrementally compile projects,
2. Use @jackkoenig code to package a jar file.
3. Also support directly run Apps and Tests from bloop.
4. The plan chain idea could be done better if have some API-level support.

**Comment by davidmlw** [comment]
> I finally get bloop work with ScalaModule, see here, https://github.com/davidmlw/api-scala-sifive/tree/bloopspace.
> 
> 1. Use bloop to incrementally compile projects,
> 2. Use @jackkoenig code to package a jar file.
> 3. Also support directly run Apps and Tests from bloop.
> 4. The plan chain idea could be done better if have some API-level support.

This wake script still cannot work. bloop compile might be parallel emitted and then bloop will generate multiple random classes dir and the python cannot package the right directory to jar.

**Comment by davidmlw** [comment]
I think I have learned a lot from job.wake, here.
https://github.com/sifive/wake/blob/96a0323d49ab12a9313ec0b4c385329e2d0f4232/share/wake/lib/system/job.wake#L549

**Comment by terpstra** [comment]
Seems to be resolved
