### ISSUE TITLE
What is the sementic of prim "hash"

### ISSUE THREAD

**Issue by davidmlw** [sifive/wake#426]
`(\_ prim "hash") (source "foo")` returns a constant number when the contents of foo changes. Is this a feature by purpose?

**Comment by davidmlw** [comment]
https://github.com/sifive/wake/blob/96a0323d49ab12a9313ec0b4c385329e2d0f4232/share/wake/lib/system/job.wake#L549-L562
Here is the hashcode that works for a file content. I would suggest that make this function global.

**Comment by terpstra** [comment]
The things you've been trying to do to circumvent wake's handling of hashes is not something I am sure I agree with. Perhaps we should have a meeting at some point to discuss the larger issue about why you needed to do it and whether or not the path you've gone is the best.
