### ISSUE TITLE
What is the best way of passing options to wake execution.

### ISSUE THREAD

**Issue by davidmlw** [sifive/wake#428]
Many build tools or languages, have a scheme to pass a define/macro/env var to the command line and select different configuration.

What is the best way of passing options to wake execution?

**Comment by davidmlw** [comment]
wake now can pass arguments to a wake function.
wake runFn foo bar # runFn will accept a list of string: "foo", "bar", Nil

**Comment by terpstra** [comment]
Is this issue resolved?
