### ISSUE TITLE
How to get the current directory that wake is invoke?

### ISSUE THREAD

**Issue by davidmlw** [sifive/wake#429]
cd root;
mkdir build; cd build; wake -x 'pwd' ## return build
cd ..; ## cd root
mkdir build2; cd build2; wake -x 'pwd' ## return build2

I see lots of cases that related with a buildRootDir, which has to be silent consistant in very wake files. If this feature is supported, then a build tree can be more easily managed.

This is not the same of 'here'. This feature would change some things. for example, build and build2 dir are a new directories that out of wake's 'mkdir'.

**Comment by terpstra** [comment]
You are looking for `cwd`/

**Comment by davidmlw** [comment]
I just tried. `cwd` and `in` can make the build directory very flexible.

**Comment by terpstra** [comment]
Is this issue resolved?
