### ISSUE TITLE
Can doCompileC accept ofile as the object file path?

### ISSUE THREAD

**Issue by davidmlw** [sifive/wake#430]
https://github.com/sifive/wake/blob/96a0323d49ab12a9313ec0b4c385329e2d0f4232/share/wake/lib/system/gcc.wake#L27-L31

This version of doCompileC hard-coded generates object files with a path along with the cfile. While in many cases, users want to move the object files to a dedicated dir. How about add an additional arguments to doCompileC and CompileC?

**Comment by terpstra** [comment]
I would encourage you not to use these methods in gcc.wake. They exist only because they are useful in the tutorial.
