### ISSUE TITLE
Warn on unused variables

### ISSUE THREAD

**Issue by richardxia** [sifive/wake#432]
It'd be useful to warn on any unused variables, perhaps controlled by a command line flag, since sometimes when refactoring code you may forget to remove some things that are unused. I'd certainly turn this on in a CI lint check if it existed!

**Comment by terpstra** [comment]
This is a good idea. How should it work? Are 'exports' the root of uses? So any function or variable unreachable from an export is unused?

**Comment by terpstra** [comment]
Would we perhaps make an exception for function arguments named '_xyz' so that you can still document what the argument is for if you really do still want it there and unused?

**Comment by terpstra** [comment]
On this topic, what other warnings should we add?

Wake already enforces whitespace, exhaustive matches, and useless cases with errors. I'm trying to think what other things could qualify as a warning, but not an error.

Perhaps useless imports?

**Comment by richardxia** [comment]
> This is a good idea. How should it work? Are 'exports' the root of uses? So any function or variable unreachable from an export is unused?

I was actually only thinking of things within a function scope, where it's obvious that they would be unused by anything else. For example:

```wake
def myFunc x =
    def unusedValue = x + 1
    x + 2
```

I'm not exactly sure what you mean by the "exports" but I'll admit that I am a bit hazy on the new Wake 0.18 module system, so I can't remember what we're doing about scoping between modules within the same package. I definitely feel that any function that is locally scoped to a single file can be safely checked, though.


> Would we perhaps make an exception for function arguments named '_xyz' so that you can still document what the argument is for if you really do still want it there and unused?

Yes, we should do that, and there is precedence for exactly that convention in popular [Python](https://docs.pylint.org/en/1.6.0/features.html#id17),  [JavaScript](https://eslint.org/docs/rules/no-unused-vars#argsignorepattern), and [Ruby](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/UnusedMethodArgument) linters. I think normally when you use the `_` prefix override in those languages, it's because the presence of that argument is necessary for API compatibility reasons, even if that particular function doesn't make use of it.

> Wake already enforces whitespace, exhaustive matches, and useless cases with errors. I'm trying to think what other things could qualify as a warning, but not an error.

How about enforcing consistent indentation within a single file? I accidentally introduced some tabs because I was still in vim paste mode, which treats tabs literally instead of respecting my tab expansion settings, and it was only caught in code review. I am also slightly annoyed by the mixed use of 2- and 4-space indentation in a single file (and also the presence of 3-space indentation along with the other two in a particular file...).

> Perhaps useless imports?

Yes! I care about this so much that I submitted a patch to a popular JavaScript linter to fix a bug in their unused import detection.
