### ISSUE TITLE
Command line option "--strict" to remove /bin & /usr/bin from PATH

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#434]
We've found that people can choose to not be explicit about the resources that their `Job` depends on when they install programs into `/bin` and `/usr/bin`.
This can make portability and reproducibility of wake rules that use `Job` difficult.

Please provide a strictness option that sets `PATH=""` for a wake invocation, for example
```
$ wake -x 'makePlan ("/bin/sh", "-c", "echo $PATH", Nil) Nil | runJob | getJobStdout'
Pass "/usr/bin:/bin\n"
$ wake --strict -x 'makePlan ("/bin/sh", "-c", "echo $PATH", Nil) Nil | runJob | getJobStdout'
Pass "\n"
````
This would allow us to detect and migrate our jobs away from `PATH=/bin:/usr/bin`.

Once we're satisfied that all our rules are migrated we can set the option in our own regression tests

**Comment by terpstra** [comment]
Fixed by #436
