### ISSUE TITLE
Add busybox?

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#435]
I was talking with @richardxia about how we could untangle some of the build rules we see that depend on `PATH=/bin/:/usr/bin` for #434 and an idea that came up was if a statically linked busybox was included as a binary in a standard wake installation.
This would allow us to have some wake function wrappers for common shell commands like `grep`, `tar`, `find` and `sh` that we know will run everywhere regardless of what runners are available.

**Comment by davidmlw** [comment]
I build a docker image of apline wake, it is very small and just ~10Mb. That includes a busybox. But there comes out another question, how a wake in a small apline docker invokes many other resources from the host?

**Comment by mmjconolly** [comment]
This issue is not related to container strategies like docker

**Comment by richardxia** [comment]
To elaborate on @mmjconolly's comment, the goal of using busybox would not be to contain the Wake process, but rather to provide a set of core utilities that work across multiple OSs. It is very common in Wake to want to call out to certain common tools, such as `grep`, `tar`, and `find`, but relying on the host OS's installation of those tools may lead to build rules that are not portable. If we were to package busybox with Wake distributions, then we could rely on a known, common implementation of those tools and their command line interfaces.

**Comment by terpstra** [comment]
This is interesting. If we improve wake-fuse to unshare the rootfs, we could also have it use this included busybox rootfs. This is all very linux specific, but I have mostly come to agree with you guys that really, excellent linux support cannot be held hostage to bsd/osx support.

**Comment by richardxia** [comment]
Is it possible to compile BusyBox for macOS as well? I just found https://github.com/daliworks/busybox-osx, but it doesn't look like it has many stars, and it hasn't been updated since 2015.

**Comment by terpstra** [comment]
So. I think it's time to revisit this idea.

I don't think the busybox mini rootfs and/or runner that triggers it necessarily belong in the wake repository. However, I do think we should beef up the wake-fuse runner to the point where it can setup a chroot to a requested root filesystem. Then a small auxiliary project could provide an appropriate sandbox runner.

This change should probably happen with the long overdue runner API rework.

**Comment by mmjconolly** [comment]
This has been implemented in a more general way than just adding busybox, we can now load a whole rootfs (which may or may not contain busybox) with which to base the sandbox on, thus hiding the host's /bin & /usr/bin  https://github.com/sifive/wake/pull/559
