### ISSUE TITLE
How wake rm intermediate files

### ISSUE THREAD

**Issue by davidmlw** [sifive/wake#437]
Currently wake records all the intermediate files and hashes them to a chain. But what if remove some intermediate files? I found that the following codes with linux `rm` not working. Actually, maybe `delete` should be a Wake API, and even the file is deleted, the hash code and hash chain is still recorded in the database. And further more, wake can provide a scheme to re-run the specific jobs to recover the deleted file. 

```
## not working code, "rm: cannot remove 'hello': Permission denied"
global def run args =
  def touch filename =
    makePlan ("touch", filename, Nil) Nil
    | runJob
  
  def delete file =
    makePlan ("rm", file.getPathName, Nil) (file, Nil)
    | runJob
  
  touch "hello"
  | getJobOutputs
  | head
  | omap delete
```

**Comment by terpstra** [comment]
Currently, you can't delete intermediate files. Why do you need to do this?

**Comment by davidmlw** [comment]
I dont have immediate requirement for now, while I forsee some applications. For example, wake may generate a bunch of huge test cases and only need to know whether it is passed. For the sake of saving disk space in the build process, wake can remove the intermediate result file when the test case is passed.

**Comment by terpstra** [comment]
I would propose that in that scenario, you delegate the job of running, checking, and redacting the output to a small shell script which wake then invokes.
