### ISSUE TITLE
A method to support soft dependencies, for example an "isDefined"

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#441]
Sometimes a user wants to have a soft dependency, perhaps they don't need a component or they're not allowed to access the component.
If there are wake rules associated with the component then we need a way to be able to call them, or not, depending on their existence.

For example
```
$ tree workspace/
workspace/
├── repo1
│   └── rules.wake
├── repo2
│   └── rules.wake
└── repo-restricted
    └── <missing>
```
`repo1/rules.wake` may want to contain `addRestrictedThingToArtifact` which is defined in `repo-restricted` but not force the user to have `repo-restricted` available, perhaps building the artifact in a gracefully degraded way

**Comment by terpstra** [comment]
The blessed way to achieve this is via publish/subscribe.

You create a package 'crypto-api' which defines a tuple type 'CryptoPlugin', perhaps with an encrypt and decrypt function plus some meta-data. The 'crypto-api' package also defines a 'plugin' topic of the tuple type.

To implement the API, you write an 'AES' package which supplies the functions and meta-data to instantiate the tuple and then publishes that tuple to the topic.

Finally, you can 'subscribe plugin' from a third package. This package depends on the plugin API package, but does not need to anything about the AES package. It interacts with all the plugins available from the subscribe.

That said, this is not really ideal for a simple "does package X have symbol Y?"  I think the thing you'd run afoul of is that you can't even `import` symbols from a package that does not exist. So it's not clear how a syntax for that should work...

**Comment by terpstra** [comment]
From what I've seen, you seem to be doing fine with publish/subscribe now. So I'm going to provisionally close this issue.
