### ISSUE TITLE
wake sandbox, option to map build directory

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#451]
It could be nice to have fuse-wake map a build directory to another part of the filesystem if we're trying to work with remote execution, caching tools, or trying to make a build more reproducable.

From what I understand the use of `workspace/build` is just convention, so it could need to be configureable.
Here's a strawman invocation:
```
wake --map $PWD/build:/build -x doFoo
```

**Comment by richardxia** [comment]
> From what I understand the use of `workspace/build` is just convention

Yes, that is just a convention.

I'm not sure if it makes sense to make this a command-line argument, since you are not necessarily always running with fuse-wake or anything that is actually capable of remapping directories, so this seems like it should be something configured by the runner itself.

**Comment by terpstra** [comment]
What I had in mind was to just take an option from the json file fed to fuse-wake which tells it where to 'mount' the fuse-backed workspace. Right now it mounts it overtop of the real workspace, but you can see I have a placeholder for that location in the current unshare PR. I think it may make sense to bind a tmpfs overtop the real workspace to completely hide it in this case.

What did you guys have in mind?

**Comment by terpstra** [comment]
The FHS spec requires the existence of `/mnt`, so perhaps that is a good place to put the workspace?

On the other hand, I wonder if we should be trying to replace the entire environment in these remote build scenarios.

**Comment by mmjconolly** [comment]
> What I had in mind was to just take an option from the json file fed to fuse-wake which tells it where to 'mount' the fuse-backed workspace. 

That sounds reasonable to me, perhaps trying to isolate just the build directory was a bit too specific

> I think it may make sense to bind a tmpfs overtop the real workspace to completely hide it in this case.

Also sounds good

**Comment by terpstra** [comment]
What makes this tricky is that we cannot support these sorts of features without unshare. :-/ Are there any cloud CI systems out there which this stuff will work under?

**Comment by richardxia** [comment]
I think all the major cloud CI vendors will provide full VMs, including CircleCI, but we're specifically using Docker here in the wake.git repo because it's really quick and easy to do builds on many old versions of CentOS, Ubuntu, and Debian.

**Comment by mmjconolly** [comment]
> The FHS spec requires the existence of `/mnt`, so perhaps that is a good place to put the workspace?

`/tmp/wake` could be nice if an unpriveliged user ever wants to manually recreate file paths debugging something

> On the other hand, I wonder if we should be trying to replace the entire environment in these remote build scenarios.

Also nice to have, though I'm thinking more narrowly of enabling incremental increases in sandboxing so we can adapt our build rules as we go

**Comment by terpstra** [comment]
I totally agree we should not enforce all-or-nothing sandboxing, but provide a spectrum of options.

The problem with `/tmp/wake` is that it might not be a directory and/or might be owned by another user. This is especially true if you imagine people putting a symlink there to point at the workspace in their home directory. To get 're-entrance' for the workspace, I think maybe we should have a 're-enter-environment' command that you can run to go into the FS view the job had both before/after it ran.

**Comment by mmjconolly** [comment]
> The problem with `/tmp/wake` is that it might not be a directory and/or might be owned by another user. 

I think you can work around that by a sequence like
1. unshare mount namespace
2. mount tmpfs over /tmp 
3. mkdir /tmp/wake
4. mount $workspace on /tmp/wake

> I think maybe we should have a 're-enter-environment' command that you can run to go into the FS view the job had both before/after it ran.

Also good to have, I'm mostly thinking that a user might get confused if there's extra restriction within the `re-enter-environment` environment, such as 'does chgrp work' or whatever else might be restricted

**Comment by terpstra** [comment]
Ah. I like your idea to guarantee `/tmp/wake` is available. Can you also think of a way to make it possible for two users on the same server to point /tmp/wake at their home directory for debug at the same time?

**Comment by mmjconolly** [comment]
> Can you also think of a way to make it possible for two users on the same server to point /tmp/wake at their home directory for debug at the same time?

Nothing comes to mind on that one (unless they really do re-enter-environment), though we have this issue regardless if we mount it somewhere else like /mnt

**Comment by terpstra** [comment]
Fixed by #463
