### ISSUE TITLE
github PR syntax highlighting

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#453]
It would be nice if github PRs that contain `*.wake` files were syntax highlighted

**Comment by terpstra** [comment]
I actually implemented a wake parser and highlighter in tree-sitter. I just did not file the appropriate github issues to get them to enable it. Linguist support has to come first, I believe.

**Comment by V-FEXrt** [comment]
> I actually implemented a wake parser and highlighter in tree-sitter
Oh! Neat. Is that still sitting around somewhere?

> It would be nice if github PRs that contain *.wake files were syntax highlighted
I think we have concluded that this really isn't possible as GitHub has stated they won't support syntax highlighting for smaller languages. We also have the in-browser extension to make this less of an issue
