### ISSUE TITLE
unconditionally sort output of `sources`

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#470]
Some anecdotes that impact using an external cache, where stability of the fuse-wake `input.json` helps

Some rules directly `write` files based on output from `sources`, 
others might embed file names (as strings) in the `Plan`'s `command`

**Comment by terpstra** [comment]
I thought it already was sorted. Do you have an example where it is not?

**Comment by mmjconolly** [comment]
I'm going off an anecdote, but I also looked at the c++ `static PRIMFN(prim_sources) {` and wakelang `export def sources dir filterRegexp =` and didn't see a sort method in there

**Comment by terpstra** [comment]
The promises list [low, high) is supposed to be sorted. That is why the 'std::lower_bound' (a binary search) works. It then runs the FullMatch regexp test on each term of the sorted list in order and pushes onto 'found'. So, ... it is already sorted.

**Comment by terpstra** [comment]
The actual sorting is done in prim_add_sources:
```
  std::sort(low, high, promise_lt);
```

**Comment by terpstra** [comment]
It would be helpful if you could chase down those anecdotes. There might be a real bug somewhere.

**Comment by terpstra** [comment]
Desired behaviour is actual behaviour.
