### ISSUE TITLE
fuse-wake sandbox: option to mount a squashfs file at mountpoint

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#475]
Toolchains could become self-contained units of distribution

Say if we had a tool on our filesystem that we custom installed at `/opt/corp/foo/` we could mksquashfs that tool as `foo.squashfs` and provide it's location to a runner which can then mount it (at say `/opt/wake/tools/foo`) within the sandbox container at a known location.

**Comment by terpstra** [comment]
I think this is done, right? 
Can you link it to the PR which fixed the issue, please.

**Comment by mmjconolly** [comment]
Wakebox (a fuse-wake extension) can mount a squashfs file, thus allowing a toolchain to be a self-contained unit https://github.com/sifive/wake/pull/565
