### ISSUE TITLE
Warn on unused import

### ISSUE THREAD

**Issue by richardxia** [sifive/wake#483]
Thanks for implementing https://github.com/sifive/wake/issues/432. However, I've noticed that Wake isn't detecting when an imported name is not used.

Here's a short example for reproducing the problem:

```wake
# foo.wake
package foo

export def myVal = "foo"
```

```wake
# bar.wake
package bar

from foo import myVal
```

```sh
$ wake --in wake -x Unit
Directory  has wakefiles with both package 'bar' and 'foo'. This prevents default package selection; defaulting to no package.
Unit
```

This is on Wake 0.19.1.

**Comment by terpstra** [comment]
Sure. I did not implement that yet.

**Comment by V-FEXrt** [comment]
Working on this off-and-on. Turns out to be harder than it looks on the surface. Feel free to follow along at #1089

**Comment by V-FEXrt** [comment]
Done! It doesn't check for `_` imports or constructor imports but should cover everything else!

**Comment by richardxia** [comment]
Awesome, thank you so much for implementing this!
