### ISSUE TITLE
Don't optimize away calls to 'panic'

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#492]
Calls to panic should always stop all execution asap.

I don't know for sure if it's related to the optimization, but the snippet below makes me think that.

```
$ cat foo.wake 
global def testfn str =
  def _ = panic "foo"
  println str

$ wake -x 'testfn "aaa"'
aaa
Unit

$ wake --no-optimize -x 'testfn "aaa"'
PANIC: foo
Requirement !panic_called failed at src/exception.cpp:69
```

**Comment by terpstra** [comment]
This is actually by design. You should not be using `panic` for error reporting. Its purpose is to mark unreachable / impossible code. With that in mind, you do want it to be optimized away if unreachable. If you had used the result of `panic`, instead of assigning it to `_`, it would have panic'd.

**Comment by terpstra** [comment]
Resolution: don't use panic except to mark unreachable / impossible outcomes. It is not an error reporting mechanism.

**Comment by mmjconolly** [comment]
It's not always feasible to return the panic type

**Comment by terpstra** [comment]
`panic` exists solely to mark unreachable branches in `match` expressions. It does not mean "stop my build". I suppose I could rename it.

**Comment by terpstra** [comment]
The "stop my build" aspect of `panic` is just a consequence of misusing `panic`.
You put it somewhere which should be unreachable, and yet it was reached.

**Comment by terpstra** [comment]
Let me try phrasing this differently:
- A correct wake program never executes `panic` (ie: the author proved all call sites are unreachable)
- Wake trusts the author that these `panic`s are unreachable and may optimize accordingly
- If you were wrong (ie: a `panic` IS reachable), then your program has undefined behavior
- Therefore, it is legal for wake to behave differently when optimization levels are changed

**Comment by terpstra** [comment]
Perhaps we should rename `panic` to `unreachable`?

**Comment by mmjconolly** [comment]
My motivation isn't to handle unreachable, it's that we still need a 'stop my build' that works anywhere

**Comment by terpstra** [comment]
Ok, but that facility is not `panic` as it exists today.

We should discuss how the facility you want to add would work, and then, assuming everyone agrees it is a good idea, add it.
