### ISSUE TITLE
claimFileAsPath fails if destination directory doesn't exist

### ISSUE THREAD

**Issue by richardxia** [sifive/wake#493]
Because `claimFileAsPath` just tries to do a straight `ln -f` from the source to the destination, it will fail if the parent directory of the destination doesn't exist. This is pretty problematic because there isn't a way to pre-create the directory and pass it in, because `claimFileAsPath` does not accept any arguments for visible files. You have to trick Wake into thinking that there is a data dependency between creating the destination directory and calling `claimFileAsPath` or else there is no guarantee that your `mkdir` will run before `claimFileAsPath`.

**Comment by mmjconolly** [comment]
claimFileAsPath also assumes hardlinks are possible
