### ISSUE TITLE
Wake considers submodule directories to be source files

### ISSUE THREAD

**Issue by terpstra** [sifive/wake#497]
`git ls-files` includes submodule attachment directories in its output, but not normal directories.

As a consequence, `source "submodule"` and `sources` both return directories! This is super bad, because the modification timestamp of directories is not stable (adding a file to a directory bumps its modification time). That can lead to the same directory being treated as a source file twice.

**Comment by terpstra** [comment]
Could this be as easy as subtracting `git submodule status` from `git ls-files`?

**Comment by terpstra** [comment]
I don't really want `status`, though. That's slow. I just want a list of the direct submodules of a git repository, without any extra processing performed.

**Comment by mmjconolly** [comment]
Maybe read the .gitmodules file

**Comment by terpstra** [comment]
Is that guaranteed to have them all? Is the format stable?

**Comment by terpstra** [comment]
Looks like it does and is! That's exactly what I need. Thanks.

**Comment by mmjconolly** [comment]
Assuming the index is clean for that file

**Comment by terpstra** [comment]
Sweet: `git config --name-only --get-regexp '^submodule[.].*[.]url'`

**Comment by terpstra** [comment]
The manpage for .gitmodules pointed out it was a git-config formatted file. :)

**Comment by mmjconolly** [comment]
`.path` I think

**Comment by terpstra** [comment]
Oddly that does not seem to work with git-config.

**Comment by terpstra** [comment]
BAM: `git config -f .gitmodules --get-regexp '.*[.]path$'`

**Comment by mmjconolly** [comment]
I don' know if you care about recursive submodules,
.gitmodules only contains a repository's direct submodules, so you may need to `find` them all

**Comment by terpstra** [comment]
I actually only want the direct submodules. wake crawls the submodules itself, so it will inspect their .gitmodules later.
