### ISSUE TITLE
Wake Tutorial curl download error

### ISSUE THREAD

**Issue by KingFrige** [sifive/wake#498]
`curl` can't download, maybe need `wget`
--------------------------------------------------------

[curl demo](https://github.com/sifive/wake/blob/master/share/doc/wake/tutorial.md#dynamically-creating-a-header-file)

error
-------
```
/usr/bin/curl -o UnicodeData.txt ftp://ftp.unicode.org/Public/UNIDATA/UnicodeData.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (9) Server denied you to change to the given directory
""
```

**Comment by terpstra** [comment]
Looks like that URL is no longer valid. Serves me right for including a URL I don't control in documentation.

**Comment by KingFrige** [comment]
wget can download
