### ISSUE TITLE
Header file inclusion in wake

### ISSUE THREAD

**Issue by abdulrauf-lm** [sifive/wake#514]
Hey, I am working on IP onboarding using the example of your PIO block onboarded tutorial. I have successfully onboarded IP and also an UVM-based VIP with it. Now I am trying to test the whole SoC environment, by running C-tests. Up til now, everything is going smoothly.
But the problem is VIP environment needs the same data run on Core by the C-test to check DUT response with C-test input. For data communication between the C-test file and UVM VIP environment, I have used the DPI-C property of SV to communicate data between C-tests and SV. But DPI is not running on Rocket-chip Core which has an onboarded IP. 
The error is that the DPI is not integrating with the SoC environment

**Comment by mmjconolly** [comment]
This github project is for the wake software tool itself, any development projects that happen to use wake are out-of-scope
