### ISSUE TITLE
Mem bytes field in Wake database incorrect

### ISSUE THREAD

**Issue by richardxia** [sifive/wake#530]
It seems like the "Mem bytes" field in the Wake database, as reported by commands such as `wake -o`, `wake --failed`, etc. is incorrect. I've been debugging an out-of-memory issue, where I'm running a Java process (FIRRTL) which has high memory usage requirements, and although I am pretty sure it is using between 5-7 GiB of memory, the Wake database is reporting around 3 <i>mega</i>bytes of memory.

**Comment by terpstra** [comment]
Apparently, "On Linux, the value returned in getrusage().ru_maxrss is in kilobytes.  On OS-X it is in bytes.  Ideally, this could be put into the documentation, but at least remove the inaccurate recommendation to multiply maxrss by page size"

**Comment by terpstra** [comment]
So I need an ifdef-controlled multiplier.

**Comment by terpstra** [comment]
According to some googling, FreeBSD also uses kilobytes. Solaris uses pages. Sigh.
