### ISSUE TITLE
Remove setPlanLocalOnly from installAs function

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#531]
`installAs` is `setPlanLocalOnly True`, I think builds will have better reliability if set to False
```
export def installAs dest file = match file.getPathResult
  Fail e = makeBadPath e
  Pass _ =
    def sdest = simplify dest
    def cmd = which "cp", file.getPathName, sdest, Nil
    def inputs = mkdir "{dest}/..", file, Nil
    def foutputs _ = sdest, Nil
    makePlan cmd inputs
    | setPlanEnvironment Nil
    | setPlanLocalOnly True
    | setPlanFnOutputs foutputs
    | runJob
    | getJobOutput
```

**Comment by terpstra** [comment]
Could you elaborate on what you see as the trade-off? Here's my take:

Pro-LocalOnly-True:
- running `cp` on a remote sandbox wastes resources (copying to/from a remote system)
- it's faster to just run it locally

Pro-LocalOnly-False:
- we don't want to encourage use of LocalOnly, and this sets a bad example

Have I missed any? Could you elaborate on the reliability impact?

**Comment by mmjconolly** [comment]
I think there's a few lines of thought in there

* I mean LocalOnly in terms of sandbox/no-sandbox, rather than remote/not-remote, I agree that it probably doesn't make much sense to run this particular job remotely
* LocalOnly perhaps should _only_ mean 'not-remote', but currently means 'no-sandbox', maybe we should have a separate switch for the two axis
* External programs should have a really good reason for escaping the sandbox, I don't think we have one here
* I guess it does set a bad example

**Comment by terpstra** [comment]
I'm closing this. When we update the Plan API, this (along with many other) callsite will get updated.
For now, I believe it does the right thing.
