### ISSUE TITLE
Expose fuse-wake executable on installed PATH

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#547]
To help users reproduce the sandbox environment,
please install (or symlink) `fuse-wake` (or a shell wrapper called `wake-sandbox`?) into the same location as the `wake` executable.

Additionally, it may be helpful to have an option to not unlink the in/out files in `.build`, as they're also useful for debugging with `fuse-wake`

**Comment by terpstra** [comment]
This was done in #621
