### ISSUE TITLE
Make the MacOS build test a 'required' test for CI

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#588]
As the MacOS test is a github test rather than circle ci, the current required `ci/circleci: release` test doesn't know about the github test

**Comment by terpstra** [comment]
Should we just switch everything to github actions? This is the only SiFive repository using circle CI. It was an interesting experiment, but the nail that sticks out gets hammered down.

**Comment by mmjconolly** [comment]
Github actions has a very limited set of operating systems

I guess we could use docker, but that's not as representative of a test when using user namespaces

**Comment by terpstra** [comment]
I've made the github action required for PRs to pass, without changing to github actions from circle CI.
