### ISSUE TITLE
Wake Share Database

### ISSUE THREAD

**Issue by benjamin-semifive** [sifive/wake#602]
I've heard SiFive is working on `Share Persistence`. I was wondering what if we can copy the `wake.db`.

Assume we have,
`wake --init --wtih=</path/to/original/directory>`, which indicates copying `wake.db` from `</path/to/original/directory>` to current dir.

When using the outputs from original ws, we may use file from `</path/to/original/workspace/build/file>`. This indicates `files` table may include `workspace column`.

If this idea doesn't fit to your side, you may close it.

**Comment by terpstra** [comment]
The idea for shared persistence is to store the information in a cache outside of the wake.db (preferably accessible via the internet).
wake.db is intended to describe the state of your workspace, so I don't think we'd want to share that directly.
