### ISSUE TITLE
Support Type Annotations

### ISSUE THREAD

**Issue by jackkoenig** [sifive/wake#609]
The hardest thing in reading Wake code is understanding the types of functions. Being able to specify types via `: <type>` (or some other style) would be so helpful.

While it would be ideal if this feature were supported across all features, I think just getting it on defined `defs` is useful enough to be worth doing even if it's harder to support anonymous functions or match statements. 

This issue https://github.com/sifive/wake/issues/369 suggests that this feature is already supported to some extent, but trying it out didn't seem to work.

**Comment by terpstra** [comment]
What is currently supported is using `:` on EXPRESSIONS, but not patterns.

So, this is legal:
```
def x = someFn 42 : List String
```

However, this is NOT legal:
```
def x : List String = someFn 42
```

... unfortunately, I think you would agree the second example is the more useful one. It would let you do this:
```
def (myFun a:Integer b:String): String = "{str a}-{b}"
```

**Comment by terpstra** [comment]
Alternatively, if we flip the priority of `:`, you could use this syntax:
```
def myFun (a:Integer) (b:String) : String = "{str a}-{b}"
```

Which priority is preferable? Probably the second?

**Comment by terpstra** [comment]
If we're going to go through the wake standard library and restyle it and add proper documentation, I think adding types to patterns should be fixed first. I'd like to find the time to just add this.

**Comment by terpstra** [comment]
Could I get a vote from @mmjconolly @jackkoenig @albertchen-sifive as to the preferred syntax?

Option 1:
```
def f (x: String) (y: String) : String = "{x}{y}
```

Option 2:
```
def f x y : String => String => String = "{x}{y}
```

Option 3:
```
def (f x:String y:String): String = "{x}{y}"
```

BTW, I just realized that this option is already legal:
```
def _ = f: String => String => String
def f x y = "{x}{y}"
```
... and this is definitely better than a simple "comment type".

**Comment by terpstra** [comment]
I'm going to put it out there that I do not like Option 2, because I do not think it works recursively.

I'd like something that works in a nested expression; ie:
```
def foo (Pair (x:String) (y:Integer)) (z:String) =
```

**Comment by terpstra** [comment]
Forget the voting. ;-)
Unless someone has a really strong counter-opinion, I think Option 1 is clearly the best.
If someone wants a long-form type definition, they can already do it with a `def _ = f : type`

**Comment by mmjconolly** [comment]
I'd like to vote against option 3
not a strong opinion about 1&2

**Comment by jackkoenig** [comment]
I'd vote for Option 1 anyway
