### ISSUE TITLE
State file outputs not ignored

### ISSUE THREAD

**Issue by albertchen-sifive** [sifive/wake#65]
With the following wake file
```
global def example _ =
  def cmdline = which "gcc", "main.c", "-o", "asdf", Nil
  def inputs = makeStatePath "asdf", sources here 'main\.c'
  makePlan cmdline inputs
  | runJob
```

I get the following result.
```
$ wake example Unit
/usr/bin/gcc main.c -o asdf
File output by multiple Jobs: asdf
```

The expected behavior is that gcc runs with no error and does not list `asdf` as an output.

**Comment by terpstra** [comment]
Actually, now I'm not sure this is a bug. The runner was correct: gcc DID output that file. Indeed, to get the updated state-file returned by a remote runner, you NEED asdf to be listed as an output.

Perhaps setPlanFnOutputs needs to be set to a filter for state files. I probably argued before that the Runner could subtract visible files from outputs automatically. However, if we adopted that policy, misbehaving tools that would not be detected by wake.
