### ISSUE TITLE
Method to obtain command line used to invoke wake

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#673]
It would be nice to be able to retrieve the command line arguments given to wake from within wake.

**Comment by terpstra** [comment]
I am going to add this information into the database, so it is available for downstream tooling.

I'm not sure that I want to supply it to the wake runtime, however. My rationale is that in the future, we will want multiple invocations of wake to be able to run sharing the same runtime... and this would then be ambiguous.

**Comment by terpstra** [comment]
(Not sure why this got closed)
