### ISSUE TITLE
installAs doesn't rerun when inputs are changed

### ISSUE THREAD

**Issue by richardxia** [sifive/wake#733]
Given the following files:

### foo.wake
```wake
package foo
from wake import _
export def test _ = installAs "{here}/bar.txt" (source "{here}/foo.txt")
```
### foo.txt
```
Hello
```

If you run `wake --in foo test`, it will create a `bar.txt` with the expected output. However, if you modify foo.txt, such as to add " World" to it, when you rerun `wake --in foo test`, it will not modify `bar.txt`.

This is with wake 0.21.0~alpha.223+g710e590.

**Comment by terpstra** [comment]
I just followed these exact steps, and it worked for me. Are you sure?

**Comment by richardxia** [comment]
I swear I tested this, but it's not failing for me anymore. Let me see if I can figure out how to reproduce what I was seeing.

**Comment by richardxia** [comment]
I managed to reproduce it in one of SiFive's internal repositories, but I narrowed it down to custom runners that somehow cause the issue, since when I delete all the custom runners, it's no longer an issue. Let me close this and file an internal ticket.
