### ISSUE TITLE
segfault with invalid match statement

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#739]
```
$ cat foo.wake
def _ = 
    match a.b a.c
            (Pass _) (Pass _) = ""
            _                 = Unit

$ wake -x Unit
Segmentation fault (core dumped)
```

**Comment by mmjconolly** [comment]
appears fixed in 0.22

**Comment by mmjconolly** [comment]
The error message isn't great though
```
$ wake -x Unit
>>> Aborting without execution <<<
```

**Comment by terpstra** [comment]
Yuck. Thanks for the report. I'll investigate later today.

**Comment by terpstra** [comment]
Took me a while to figure out what the actual bug in that code was: a missing `_` on the second line!

So the problem is it does not complain properly when the arity is mismatched.

**Comment by terpstra** [comment]
Reduced bug example:

```
def _ = 
  match 1 1
    _ _ = "2"
    _ = "1"
```
