### ISSUE TITLE
Documentation is not properly attached to binary infix functions

### ISSUE THREAD

**Issue by ag-eitilt** [sifive/wake#769]
The LSP attaches documentation to the first symbol in a `def` statement.  This is normally reasonable, but with binary functions named using symbols, any comment block on preceding lines gets attached to the first parameter rather than the function itself; in the below, the comment winds up documenting `a` rather than `⊆`.

```
# Test if `a` is a subset of `b` (every element of `a` is also in `b`).
# Note that the comparison function of `b` is used to determine element
# equality, if the two differ. See `tsubset` for a prefix form of the function.
export def (a: Tree x) ⊆ (b: Tree x): Boolean =
    tsubset a b
```

**Comment by terpstra** [comment]
Nope. You're right. Shocking. @elena-pudovkina fix please. :)
