### ISSUE TITLE
Symbol rename doesn't understand Unicode characters

### ISSUE THREAD

**Issue by ag-eitilt** [sifive/wake#770]
The F2 symbol renaming feature of the VS Code extension works quite well in the general case, but seems to mix locating references by counting bytes and counting characters.  When the line contains Unicode characters to the left of the reference, the replacement is offset to the right; when the old name contains more Unicode characters than the new, additional characters are deleted at the end of the symbol.  (The case of the new name containing more Unicode than the old is handled correctly.)

**Comment by terpstra** [comment]
The bug is in src/util/file.cpp:76:
```
        size_t col = 1 + (offset - *it);
```
... the column count has to consider multibyte characters.
