### ISSUE TITLE
Type errors with 'topic' are reported poorly

### ISSUE THREAD

**Issue by ag-eitilt** [sifive/wake#805]
When an object is `publish`ed to a topic with the wrong type, the type mismatch error points to the topic definition rather than the `publish` call; this is a particular issue when you want to change the type of the topic itself; you can get many errors all pointing to the same line and have to resort to a project-wide search to find everywhere that needs fixing ("Go to References" also doesn't work for topics, though I imagine that's due to them being a bit type-like).  A smaller issue is that the underlying `List` representation is printed in the error message, so you have "does not match explicit type ascription of: `List a`" when you've only written `topic accum: a`.

**Comment by terpstra** [comment]
Thank you for the report. The type ascription is clearly being inserted at the wrong location. :-(
