### ISSUE TITLE
LSP: documentation hover broken for `tuple` and `data`

### ISSUE THREAD

**Issue by terpstra** [sifive/wake#820]
The current approach to linking documentation comments to definitions works great for normal top-level `def`s.

However, when a comment precedes a `data` or `tuple` definition, several symbols are introduced. The LSP currently only associates the comments to the first such symbol.

For example,
```
# This comment only shows up for `Nil`, not for `,` (also not `List`)
export data List a =
    Nil
    (head: a), (tail: List a)
```

Another example.
```
# This comment only shows up for Pet, not `getPetName` or `getPetAge`
tuple Pet =
  Name: String
  Age: Integer
```

**Comment by terpstra** [comment]
Example:
```
# Some comment
data Animal a =
  Dog (name: String) (label: a)
  Cat
```

That introduces two kinds of things:
- the type `Animal`
- The constructors `Dog` and `Cat` (which also act as destructors)

... the comment currently only gets bound to the type, and there is no way to associate a comment to the other two things. Maybe they should all use the same comment? Maybe they should have individual comments? No idea. Decide for me.

Example:
```
# Some comment
tuple Cat =
  Name: String
  Tag: Integer
```

That introduces three things:
- the type `Cat`
- the (de)constructor `Cat`
- helper methods: {get,set,edit}Cat{Name,Tag}

Currently, the type and constructor (Cat) have the same location, so the LSP conflates them as the same thing. Unfortunately it seems the comment got associated to the type, but all mouse overs use the constructor, so NOTHING gets a comment, currently. Certainly, both the type and constructor should have the comment that proceeded the tuple definition. Also, the elements of the tuple get no comment. They should get some kind of comment.

**Comment by ag-eitilt** [comment]
I vote for individual comments for `data` constructors, both because that's what I'm familiar with from Haskell, and because that would parallel the code layout of `tuple` comments.

**Comment by terpstra** [comment]
I'm not opposed to that approach, though it means you won't get "comment sharing" for the overall intent of the type.

Imagine this:
```
# The List type can hold an ordered collection of elements of the same arbitrary type.
data List a =
  Nil # Nil is the empty List. Every List ends with a Nil.
  # The comma operator adds a new first element to a List.
  # ...
  a, List a
```

You can see that we would need to be careful with the comments. The Nil comment follows its definition, whereas the `,` comment precedes the definition. IMO, you would also ideally want to replicate the top-level `List` comment for each of the constructors. e.g., when you mouse-over `Nil` you probaly want to see:

```
Nil: List a

The List type can hold an ordered collection of elements of the same arbitrary type.
Nil is the empty List. Every List ends with a Nil.
```

**Comment by terpstra** [comment]
Actually, I guess we could just say that comments on the end of the line never appear in tool-tips. That's a simple rule to understand, and can be useful to intentionally exclude some comments from the tooltip.

In other words, you whould have written it like this:
```
# The List type can hold an ordered collection of elements of the same arbitrary type.
data List a =
  # Nil is the empty List. Every List ends with a Nil.
  Nil
  # The comma operator adds a new first element to a List.
  # ...
  a, List a
``` 

This does not line up with existing practice for the `tuple` member elements, though.

**Comment by terpstra** [comment]
Perhaps your comment combining concern can be addressed by reversing the order?

```
Nil: List a

Nil is the empty List. Every List ends with a Nil.

The List type can hold an ordered collection of elements of the same arbitrary type.
```

**Comment by ag-eitilt** [comment]
I like that better.  There's still a potential (very small) awkwardness if the constructor documentation has examples at the end or anything else which doesn't quite flow into the type documentation, but I think it would probably be outweighed by the benefits of having the info.
