### ISSUE TITLE
Add something as `when` keyword for each version

### ISSUE THREAD

**Issue by benjamin-jin** [sifive/wake#844]
Time to time some APIs is deleted or renamed in new version of wake. (`panic` to `unrechable`)

Isn't it better to keep the old version of API into the source code for usability?
For instance,
```
def func msg =
  when (wake_version < something)       panic msg
  when (wake_version >= something)    unreachable msg
```

Some of my team members are still using the old version of wake, but want to use wake code written in higher version.

**Comment by terpstra** [comment]
Newer versions of wake often support the APIs of older wake releases. This is controlled by the import line.

For example, if a file uses:
```
from v0_19_wake import _
```
... then `panic` is available.

Current/up-to-date wake files should use:
```
from v0_24_wake import _
```
... that way they will continue to work when the next version further changes the API.

**Comment by benjamin-jin** [comment]
Understood.
