### ISSUE TITLE
Running wake directly from the git checkout

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#848]
It's often nice to be able to run wake (including wakebox) directly from the git checkout that had `make` called in it, with each executable having the correct installed name.

We can of-course just run the `make install` step, so it's just a convenience request

**Comment by ag-eitilt** [comment]
What workflow are you imagining?  I've got Wake built on a couple systems where I just call `../wake/bin/wake` (or `./bin/wake` within the checkout) without having installed it globally.

**Comment by mmjconolly** [comment]
I think this is resolved

It used to be that if you ran `./bin/wake` it would not create things like `./bin/fuse-wake` (now wakebox) unless you ran `make install`
