### ISSUE TITLE
compile fails

### ISSUE THREAD

**Issue by pxs7** [sifive/wake#877]
compile fails due to

std=c++11 -Wall -O2 -DVERSION=v0.24.0-1-g9a8b6e7 -o bin/wake src/parser/lexer.o src/parser/parser.o src/json/jlexer.o src/util/shell.o src/util/unlink.o src/util/execpath.o src/util/file.o src/util/fragment.o src/util/rank.o src/util/mkdir_parents.o src/util/location.o src/json/utf8.o src/json/json5.o src/json/lexint.o src/json/jparser.o src/dst/todst.o src/dst/expr.o src/dst/bind.o src/optimizer/inline.o src/optimizer/scope.o src/optimizer/ssa.o src/optimizer/cse.o src/optimizer/tossa.o src/optimizer/usage.o src/optimizer/sweep.o src/optimizer/purity.o src/parser/syntax.o src/parser/cst.o src/parser/wakefiles.o src/runtime/sources.o src/runtime/prim.o src/runtime/job.o src/runtime/runtime.o src/runtime/gc.o src/runtime/double.o src/runtime/target.o src/runtime/regexp.o src/runtime/string.o src/runtime/status.o src/runtime/value.o src/runtime/exception.o src/runtime/poll.o src/runtime/database.o src/runtime/tuple.o src/runtime/vector.o src/runtime/integer.o src/runtime/json.o src/runtime/profile.o src/types/datatype.o src/types/sums.o src/types/data.o src/types/type.o src/types/internal.o tools/wake/markup.o tools/wake/describe.o tools/wake/main.o src/compat/sigwinch.o src/compat/windows.o src/compat/mtime.o src/compat/physmem.o src/compat/readable.o src/compat/utimens.o src/compat/spawn.o src/compat/aligned_alloc.o src/compat/rusage.o vendor/blake2/blake2b-ref.o vendor/utf8proc/utf8proc.o vendor/siphash/siphash.o vendor/whereami/whereami.o vendor/gopt/gopt.o vendor/gopt/gopt-errors.o vendor/gopt/gopt-arg.o  -lsqlite3   -lgmp -pthread -L/usr/local/lib -lre2   -lncurses -ltinfo  
c++ -std=c++11 -Wall -O2 -DVERSION=v0.24.0-1-g9a8b6e7 -Ivendor -Isrc tools/fuse-wake/fuse-wake.cpp src/wakefs/fuse.cpp src/wakefs/daemon_client.cpp src/wakefs/namespace.cpp src/json/jlexer.o src/util/shell.o src/util/unlink.o src/util/execpath.o src/util/file.o src/util/fragment.o src/util/rank.o src/util/mkdir_parents.o src/util/location.o src/json/utf8.o src/json/json5.o src/json/lexint.o src/json/jparser.o src/compat/sigwinch.o src/compat/windows.o src/compat/mtime.o src/compat/physmem.o src/compat/readable.o src/compat/utimens.o src/compat/spawn.o src/compat/aligned_alloc.o src/compat/rusage.o vendor/whereami/whereami.o -o bin/fuse-wake 
c++ -std=c++11 -Wall -O2 -DVERSION=v0.24.0-1-g9a8b6e7 -Ivendor -Isrc -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse   tools/fuse-waked/fuse-waked.cpp src/json/jlexer.o src/util/shell.o src/util/unlink.o src/util/execpath.o src/util/file.o src/util/fragment.o src/util/rank.o src/util/mkdir_parents.o src/util/location.o src/json/utf8.o src/json/json5.o src/json/lexint.o src/json/jparser.o src/compat/sigwinch.o src/compat/windows.o src/compat/mtime.o src/compat/physmem.o src/compat/readable.o src/compat/utimens.o src/compat/spawn.o src/compat/aligned_alloc.o src/compat/rusage.o vendor/whereami/whereami.o -o lib/wake/fuse-waked  -pthread -lfuse  
cc -std=c11 -Wall -O2 -DVERSION=v0.24.0-1-g9a8b6e7 -Ivendor -Isrc -o tools/shim-wake/shim.o -c tools/shim-wake/shim.c
cc -std=c11 -Wall -O2 -DVERSION=v0.24.0-1-g9a8b6e7 -o lib/wake/shim-wake tools/shim-wake/shim.o vendor/blake2/blake2b-ref.o 
test -f wake.db || ./bin/wake --init .
WAKE_PATH=/bin ./bin/wake build default
unshare: Invalid argument
unshare: Invalid argument
unshare: Invalid argument
unshare: Invalid argument
unshare: Invalid argument
unshare: Invalid argument
unshare: Invalid argument
unshare: Invalid argument
unshare: Invalid argument
unshare: Invalid argument
Fail (Error "Non-zero exit status (Exited 1) for '/bin/dash -c 'set -e\ngzip -dc \"src/parser/parser.cpp.gz\" > \"src/parser/parser.cpp.tmp\"\nmv \"src/parser/parser.cpp.tmp\" \"src/parser/parser.cpp\"''" Nil)

**Comment by mmjconolly** [comment]
You need to have 'user namespaces' available.
It might be that you're using an old Linux distribution, or one that prevents _unprivileged_ user namespaces

**Comment by pxs7** [comment]
> 
Yes, I am using redhat 7

how and where  can I create   'user namespaces'  ?

**Comment by pxs7** [comment]
[@localhost ~]$ uname -r
3.10.0-1127.13.1.el7.x86_64

**Comment by mmjconolly** [comment]
redhat 7 doesn't have user namespaces enabled by default, it requires some steps to enable, for example:
https://goyalankit.com/blog/user-namespace-in-red-hat-enterprise-linux-7-dot-2

**Comment by pxs7** [comment]
> redhat 7 doesn't have user namespaces enabled by default, it requires some steps to enable, for example: https://goyalankit.com/blog/user-namespace-in-red-hat-enterprise-linux-7-dot-2

when do as tutorial.md,  

    echo 'int main() { return 0; }' > main.cpp
    echo 'def build x = compileC "native-cpp11-release" ("-I.", Nil) Nil (source "main.cpp")' > tutorial.wake
    git add main.cpp
    wake build

the result is
 test/tutorial.wake:1:11: (warning) unused function argument 'x'; consider renaming to _x
test/tutorial.wake:1:[15-22]: reference to undefined variable 'compileC'
>>> Aborting without execution <<<

why compileC not found?

**Comment by ag-eitilt** [comment]
The tutorial is unfortunately a few versions out of date.  I've been working on PR #860 to correct it, but a couple other things came up to fill my time so I've not been able to finalize and merge it yet.  The [current state of the file](https://github.com/sifive/wake/blob/c660ad304b90ecab03232be470d1421b80817e91/share/doc/wake/tutorial.md) should be good enough to follow, but there might still be a rough edge here and there (let me know if you find anything!)
