### ISSUE TITLE
clang-format the entire code base

### ISSUE THREAD

**Issue by JakeSiFive** [sifive/wake#899]
We want to clang-format the entire code base, this has two strange side effects

1) We'll lose all git history but that's ok because Wes wrote the vast vast majority of the C++ code
2) Whoever does this will become the second largest contributor to wake according to github overnight :)

**Comment by mmjconolly** [comment]
For (1), it can be mitigated somewhat by https://michaelheap.com/git-ignore-rev/

**Comment by JakeSiFive** [comment]
Oh sweet I didn't know about that!

**Comment by V-FEXrt** [comment]
Is there a prefered style format?

```
 --style=<string>               - Coding style, currently supports:
                                     LLVM, GNU, Google, Chromium, Microsoft, Mozilla, WebKit.
```

**Comment by mmjconolly** [comment]
Which ever one that you can get 2 votes for out of yourself+Jake+Wes

**Comment by JakeSiFive** [comment]
Rank Choice based solely on my familiarity, I don't really care though. I think they're all '{' on the same line which is the only thing I'll scream about. I just want consistency.

1. LLVM
2. Chromium
3. Google
4. Mozilla
5. WebKit
6. Microsoft

Really anything is fine. I say you pick!

**Comment by V-FEXrt** [comment]
Personal preference is just Google + 100 chars per line due to familiarity.

From an offline chat with Jake, sounds like he is on board

**Comment by JakeSiFive** [comment]
Ashley did this!
