### ISSUE TITLE
shebang script fails with /usr/bin/env

### ISSUE THREAD

**Issue by mmjconolly** [sifive/wake#985]
If I run a wake in script mode:
```
$ cat do.wake
#!/absolute/path/to/wake -: myfunc 
global def myfunc _ =
    "echo hello"
    | makePlan "" Nil
    | runJob
    | getJobStdout
$ chmod +x do.wake
$ ./do.wake
Directory . has wakefiles with both package 'foo' and 'do.wake'. This prevents default package selection; defaulting to no package. 
Pass "hello\n"
```
It works well enough (though complains about the packages that I have in the current dir)

If I change the #! path to something more portable I get this error:
```
$ cat do.wake
#!/usr/bin/env wake -: myfunc
global def myfunc _ =
   ...as before

$ ./do.wake 
/usr/bin/env: ‘wake -: myfunc’: No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
```

Adding a `-S` doesn't appear to solve it, such as
`#!/usr/bin/env wake -S -: myfunc`

**Comment by richardxia** [comment]
`-S` has to go before the rest of the command, as it is an option of `env`.

Also, not that this is a somewhat recent addition to the `env` command, and older distros such as Ubuntu 16.04 don't support `-S`.

**Comment by mmjconolly** [comment]
ah you're right, I didn't read the error well enough to see it was coming from env rather than wake
`#!/usr/bin/env -S wake -: myfunc` works
